Repository mozilla/blurts-server, pull requests merged in 2019-02, with the labels that each got.

#722 for #677 More Firefox Account integration
  controllers/home.js
  controllers/oauth.js
  controllers/scan.js
  hbs-helpers.js
  hibp.js
  locales/en/app.ftl
  modified-strings.js
  package.json
  public/css/app.css
  public/css/fxa.css
  public/img/sprites.svg
  public/img/x-close.svg
  public/js/monitor.js
  routes/scan.js
  tests/controllers/home.test.js
  tests/controllers/oauth.test.js
  tests/controllers/scan.test.js
  views/layouts/default.hbs
  views/monitor.hbs
  views/partials/banners/download_firefox_banner.hbs
  views/partials/banners/download_firefox_bar.hbs
  views/partials/banners/sign_up_banner.hbs
  views/partials/compromised_accounts.hbs
  views/partials/firefox_monitor_logo.hbs
  views/partials/footer.hbs
  views/partials/fxa_enabled/breached_account.hbs
  views/partials/fxa_enabled/fxa_monitor.hbs
  views/partials/fxa_enabled/fxa_new_user_bar.hbs
  views/partials/fxa_enabled/fxa_scan.hbs
  views/partials/fxa_enabled/fxa_sign_up_banner.hbs
  views/partials/fxa_enabled/menu/fxa_links.hbs
  views/partials/fxa_enabled/menu/fxa_menu_icon.hbs
  views/partials/fxa_enabled/menu/fxa_mobile_menu.hbs
  views/partials/fxa_enabled/menu/fxa_navigation.hbs
  views/partials/fxa_enabled/scan_results/fxa_compromised_accounts.hbs
  views/partials/fxa_enabled/scan_results/result_headline.hbs
  views/partials/fxa_enabled/scan_results/result_page_right.hbs
  views/partials/fxa_enabled/scan_results/result_subhead.hbs
  views/partials/fxa_enabled/scan_results/single_breach.hbs
  views/partials/fxa_enabled/see_full_report_button.hbs
  views/partials/fxa_enabled/sign_up_bundle.hbs
  views/partials/header.hbs
  views/partials/legacy/compromised_accounts.hbs
  views/partials/legacy/legacy_footer.hbs
  views/partials/legacy/legacy_header.hbs
  views/partials/legacy/legacy_monitor.hbs
  views/partials/legacy/scan.hbs
  views/partials/password_tips.hbs
  views/partials/scan_another_email.hbs
  views/partials/scan_form.hbs
  views/partials/sign_up_button.hbs
  views/partials/sprite.hbs
  views/partials/what_to_do.hbs
  views/scan.hbs
Labels: feature-fxa, review

#740 fix #739 - use matrix to separate python and node
  .travis.yml
  package.json
Labels: review

#758 Add devkitPro.png
  public/img/logos/devkitPro.png
Labels: review

#751 Remove unused logo images.
  public/img/logos/2844Breaches.png
  public/img/logos/AntiPublic.png
  public/img/logos/B2BUSABusinesses.png
  public/img/logos/DataEnrichment.png
  public/img/logos/Digimon.png
  public/img/logos/ElasticsearchSalesLeads.png
  public/img/logos/ExploitIn.png
  public/img/logos/KayoMoe.png
  public/img/logos/NetProspex.png
  public/img/logos/OnlinerSpambot.png
  public/img/logos/Pemiblanc.png
  public/img/logos/RiverCityMedia.png
  public/img/logos/SCDailyPhoneSpamList.png
  public/img/logos/SaverSpy.png
  public/img/logos/SpecialKSpamList.png
  public/img/logos/TrikSpamBotnet.png
  public/img/logos/VINs.png
Labels: review

#754 https://nvd.nist.gov/vuln/detail/CVE-2018-16487
  package-lock.json
  package.json
Labels: review, security

#750 HIBP attribution updates.
  public/css/fxa.css
  views/partials/fxa_enabled/fxa_monitor.hbs
  views/partials/fxa_enabled/scan_results/fxa_compromised_accounts.hbs
  views/partials/fxa_enabled/scan_results/single_breach.hbs
  views/partials/hibp_attribution.hbs
Labels: review

#759 Delete stale `fxa_navigation.hbs` dupe.
  views/partials/fxa_enabled/fxa_navigation.hbs
Labels: review

#760 Use #loop to loop through unsub_reasons and cleanup.
  controllers/user.js
  tips.js
  unsubscribe_reasons.js
  views/partials/subpages/unsubscribe_survey.hbs
Labels: review

#761 Condense {{>breach_listing}} and {{>breached_account}} partials.
  views/partials/breach_listing.hbs
  views/partials/fxa_enabled/breached_account.hbs
  views/partials/fxa_enabled/scan_results/fxa_compromised_accounts.hbs
  views/partials/legacy/compromised_accounts.hbs
Labels: review

#747 fix #688: add csrf & encrypted page tokens for scans
  .env-dist
  app-constants.js
  controllers/home.js
  controllers/scan.js
  locales/en/app.ftl
  package-lock.json
  package.json
  routes/home.js
  routes/scan.js
  server.js
  tests/controllers/home.test.js
  tests/controllers/scan.test.js
  views/partials/scan_form.hbs
Labels: review

#764 Capitalize the sign in button in en locales.
  public/css/fxa.css
  public/js/monitor.js
Labels: review

#765 Consolidate scan result logic for easier current/future templating.
  controllers/home.js
  controllers/oauth.js
  controllers/scan.js
  controllers/utils.js
  public/css/fxa.css
  routes/scan.js
  scan-results.js
  tests/controllers/home.test.js
  tests/controllers/oauth.test.js
  tests/controllers/scan.test.js
  views/partials/fxa_enabled/fxa_new_user_bar.hbs
  views/partials/fxa_enabled/fxa_scan.hbs
  views/partials/fxa_enabled/scan_results/fxa_compromised_accounts.hbs
  views/partials/fxa_enabled/scan_results/result_headline.hbs
  views/partials/fxa_enabled/scan_results/result_page_right.hbs
  views/partials/fxa_enabled/scan_results/result_subhead.hbs
  views/partials/fxa_enabled/scan_results/single_breach.hbs
  views/partials/fxa_enabled/see_full_report_button.hbs
  views/partials/legacy/compromised_accounts.hbs
  views/partials/legacy/scan.hbs
Labels: review

#776 fix #775: dev, heroku, and stage don't need to force https
  server.js
Labels: review

#792 use npm-audit-ci-wrapper to set fail threshold
  package-lock.json
  package.json
Labels: :wrench: tooling, review

#800 fix #799: Add markup to { $breachCount } after grabbing localized strings.
  hbs-helpers.js
Labels: review

#798 Add MyHeritage breach logo
  public/img/logos/MyHeritage.png
Labels: review
