Repository mozilla/blurts-server, pull requests merged in 2023-11, with the labels that each got.

#3683 Import translations from l10n repository (2023-11-01)
  locales/gn/app.ftl
Labels: l10n

#3687 Import translations from l10n repository (2023-11-02)
  locales/es-ES/app.ftl
  locales/es-ES/settings.ftl
Labels: l10n

#3690 Import translations from l10n repository (2023-11-03)
  locales/tr/settings.ftl
Labels: l10n

#3702 Make the Firefox Accounts rebrand permanent
  locales/en/app.ftl
  locales/en/settings.ftl
  src/app/(nextjs_migration)/(authenticated)/user/settings/page.tsx
  src/app/(nextjs_migration)/components/client/UserMenu.tsx
  src/db/tables/featureFlags.ts
Labels: Review: µ

#3709 Prevent flash of fallback icon on re-render
  src/app/components/client/DataBrokerImage.tsx
Labels: Review: µ

#3720 Import translations from l10n repository (2023-11-12)
  locales/pt-PT/app.ftl
  locales/pt-PT/breaches.ftl
  locales/pt-PT/data-classes.ftl
  locales/pt-PT/exposure-scan.ftl
  locales/pt-PT/landing.ftl
  locales/pt-PT/recommendations.ftl
  locales/pt-PT/settings.ftl
Labels: l10n

#3726 Import translations from l10n repository (2023-11-13)
  locales/gn/breaches.ftl
  locales/ia/app.ftl
  locales/pt-PT/breaches.ftl
  locales/zh-CN/landing.ftl
Labels: l10n

#3732 Import translations from l10n repository (2023-11-15)
  locales/sq/app.ftl
  locales/sq/breaches.ftl
  locales/sq/exposure-scan.ftl
  locales/sq/landing.ftl
  locales/sq/settings.ftl
Labels: l10n

#3735 Import translations from l10n repository (2023-11-16)
  locales/pt-PT/app.ftl
  locales/pt-PT/breaches.ftl
  locales/sq/exposure-scan.ftl
Labels: l10n

#3745 Import translations from l10n repository (2023-11-17)
  locales/cs/app.ftl
  locales/cy/app.ftl
  locales/de/app.ftl
  locales/es-AR/app.ftl
  locales/fr/app.ftl
  locales/hu/app.ftl
  locales/id/app.ftl
  locales/it/app.ftl
  locales/nl/app.ftl
  locales/pt-BR/app.ftl
  locales/pt-PT/app.ftl
  locales/sk/app.ftl
  locales/sl/app.ftl
  locales/zh-TW/app.ftl
Labels: l10n

#3762 Import translations from l10n repository (2023-11-19)
  locales/en-GB/app.ftl
  locales/es-CL/app.ftl
  locales/fi/app.ftl
  locales/pt-PT/app.ftl
  locales/pt-PT/breaches.ftl
  locales/pt-PT/data-classes.ftl
  locales/pt-PT/exposure-scan.ftl
  locales/pt-PT/landing.ftl
  locales/ru/app.ftl
  locales/sq/app.ftl
  locales/sq/data-classes.ftl
  locales/sv-SE/app.ftl
  locales/tr/app.ftl
  locales/vi/app.ftl
  locales/zh-CN/app.ftl
Labels: l10n

#3761 Raise max number of Dependabot PRs
  .github/dependabot.yml
Labels: Review: µ

#3775 Import translations from l10n repository (2023-11-20)
  locales/el/app.ftl
  locales/es-ES/app.ftl
  locales/uk/app.ftl
Labels: l10n

#3688 Add tests for getNextGuidedStep()
  src/app/functions/server/getRelevantGuidedSteps.test.ts
  src/app/functions/server/getRelevantGuidedSteps.ts
Labels: Review: XS

#3786 Import translations from l10n repository (2023-11-22)
  locales/fy-NL/app.ftl
Labels: l10n

#3760 Fix scan result cards expanding/collapsing in sync
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/RemovalCard.tsx
  src/app/components/client/ExposureCard.tsx
  src/db/tables/onerep_scans.ts
Labels: Review: XS

#3788 Import translations from l10n repository (2023-11-23)
  locales/en-CA/app.ftl
Labels: l10n

#3794 Import translations from l10n repository (2023-11-25)
  locales/ia/app.ftl
Labels: l10n

#3799 Remove workaround for incomplete jest-axe typings
  jest.setup.ts
Labels: Review: XS

#3810 Import translations from l10n repository (2023-11-28)
  locales/hu/app.ftl
Labels: l10n

#3815 Import translations from l10n repository (2023-11-29)
  locales/nn-NO/app.ftl
Labels: l10n
