Repository mozilla/blurts-server, pull requests merged in 2023-08, with the labels that each got.

#3272 Import translations from l10n repository (2023-07-31)
  locales/sv-SE/data-classes.ftl
Labels: l10n

#3271 Actually run admin check on feature flag page
  src/app/(proper_react)/redesign/(authenticated)/admin/feature-flags/page.tsx
Labels: Review: µ

#3277 Fix stories for components using useRouter
  .storybook/preview.tsx
Labels: Review: µ

#3273 Remove unused class
  src/app/components/client/ExposureCard.module.scss
  src/app/components/server/Icons.module.scss
Labels: Review: µ

#3278 Add env var required for Next-Auth to work
  .env-dist
Labels: Review: µ

#3287 Import translations from l10n repository (2023-08-03)
  locales/gn/data-classes.ftl
Labels: l10n

#3288 Animate changes in the progress bar
  src/app/components/client/ProgressBar.module.scss
Labels: Review: µ

#3291 Group related Dependabot updates
  .github/dependabot.yml
Labels: Review: XS

#3305 Import translations from l10n repository (2023-08-14)
  locales/ca/data-classes.ftl
Labels: l10n

#3308 Import translations from l10n repository (2023-08-15)
  locales/gn/settings.ftl
  locales/ppl/app.ftl
Labels: l10n

#3309 Import translations from l10n repository (2023-08-16)
  locales/th/app.ftl
Labels: l10n

#3313 Import translations from l10n repository (2023-08-17)
  locales/cy/app.ftl
  locales/de/app.ftl
  locales/es-AR/app.ftl
  locales/fr/app.ftl
  locales/hu/app.ftl
  locales/id/app.ftl
  locales/it/app.ftl
  locales/nl/data-classes.ftl
  locales/sl/app.ftl
  locales/zh-TW/app.ftl
Labels: l10n

#3324 Import translations from l10n repository (2023-08-18)
  locales/de/app.ftl
  locales/en-GB/app.ftl
  locales/fy-NL/app.ftl
  locales/fy-NL/data-classes.ftl
  locales/gn/app.ftl
  locales/sv-SE/app.ftl
  locales/uk/app.ftl
  locales/zh-CN/app.ftl
Labels: l10n

#3315 Fix warnings about unknown `onPress` attribute
  src/app/components/client/ExposuresFilter.tsx
  src/app/components/client/ProgressCard.tsx
Labels: Review: µ

#3325 Remove space from filename
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/AboutBrokersIcon.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/images/about-brokers-illustration.svg
Labels: Review: µ

#3333 Import translations from l10n repository (2023-08-27)
  locales/fr/exposure-scan.ftl
Labels: l10n

#3336 Import translations from l10n repository (2023-08-29)
  locales/gn/app.ftl
  locales/gn/bento.ftl
  locales/gn/data-classes.ftl
  locales/gn/recommendations.ftl
Labels: l10n

#3343 Import translations from l10n repository (2023-08-30)
  locales/el/breaches.ftl
  locales/el/data-classes.ftl
  locales/el/exposure-scan.ftl
  locales/el/landing.ftl
  locales/el/settings.ftl
Labels: l10n

#3340 Make coverage report help find untested code
  jest.config.cjs
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/EnterInfo.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/FindExposures.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/GetStarted.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/View.tsx
  src/app/(proper_react)/redesign/MobileShell.tsx
  src/app/(proper_react)/redesign/PageLink.tsx
  src/app/components/client/Chart.tsx
  src/app/components/client/ComboBox.tsx
  src/app/components/client/ExposureCard.tsx
  src/app/components/client/ExposuresFilter.tsx
  src/app/components/client/ExposuresFilterExplainer.tsx
  src/app/components/client/InputField.tsx
  src/app/components/client/ListBox.tsx
  src/app/components/client/LocationAutocompleteInput.tsx
  src/app/components/client/Popover.tsx
  src/app/components/client/ProgressCard.tsx
  src/app/components/client/dialog/Dialog.tsx
  src/app/components/client/toolbar/AppPicker.tsx
  src/app/components/server/Icons.tsx
  src/app/components/server/StatusPill.tsx
  src/app/functions/server/featureFlags.ts
  src/app/functions/server/mockL10n.ts
  src/app/functions/universal/user.ts
  src/cloud-functions/index.js
  src/db/tables/breaches.js
  src/db/tables/emailAddresses.js
  src/db/tables/subscribers.js
  src/utils/breachLogo.js
  src/utils/breachResolution.js
  src/utils/breachSummary.js
  src/utils/email.js
  src/utils/error.js
  src/utils/fluent.js
  src/utils/formatDate.js
  src/utils/fxa.js
  src/utils/hibp.js
  src/utils/utmParams.js
Labels: Review: XS
