Repository mozilla/blurts-server, pull requests merged in 2023-07, with the labels that each got.

#3185 Import translations from l10n repository (2023-07-03)
  locales/el/exposure-scan.ftl
Labels: l10n

#3187 Move pendingTranslations.ftl
  .github/workflows/reference_linter.yaml
  locales-pending/premium.ftl
  src/app/functions/server/l10n.ts
Labels: Review: XS

#3193 Make Storybook stories cover the full screen
  .storybook/preview-head.html
  .storybook/preview.tsx
Labels: Review: µ

#3196 Restore serving logos in the free scan API
  src/app/api/v1/scan/route.ts
  src/utils/breachLogo.js
Labels: Review: XS

#3194 Fix path to version.json
  src/controllers/dockerflow.js
Labels: Review: µ

#3205 Import translations from l10n repository (2023-07-09)
  locales/pt-PT/add-email.ftl
Labels: l10n

#3209 Load the dashboard into an actual page
  locales-pending/premium.ftl
  src/app/(nextjs_migration)/(authenticated)/user/breaches/breaches.d.ts
  src/app/(nextjs_migration)/(authenticated)/user/breaches/page.tsx
  src/app/(nextjs_migration)/(guest)/breach-details/[breachName]/page.tsx
  src/app/(nextjs_migration)/(guest)/breaches/page.tsx
  src/app/(nextjs_migration)/components/server/BreachesTable.tsx
  src/app/(proper_react)/(onboarding)/user/welcome/Onboarding.stories.tsx
  src/app/(proper_react)/Dashboard.module.scss
  src/app/(proper_react)/Dashboard.stories.tsx
  src/app/(proper_react)/Dashboard.tsx
  src/app/(proper_react)/redesign/(authenticated)/admin/feature-flags/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/images/dashboard-top-banner-wave.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx
  src/app/(proper_react)/redesign/Shell.stories.tsx
  src/app/(proper_react)/redesign/Shell.tsx
  src/app/components/client/ExposureCard.module.scss
  src/app/components/client/ExposureCard.tsx
  src/app/components/client/stories/ExposureCard.stories.ts
  src/app/components/client/toolbar/Toolbar.tsx
  src/app/components/client/toolbar/UserMenu.tsx
  src/app/functions/server/getBreaches.ts
  src/app/functions/server/getUserBreaches.ts
  src/next-auth.d.ts
  src/utils/breaches.js
  src/utils/hibp.js
Labels: Review: XS

#3210 Unblock Storybook-in-tests with l10n
  .storybook/preview.tsx
  locales-pending/premium.ftl
  src/app/(proper_react)/(onboarding)/user/welcome/Onboarding.test.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
  src/app/(proper_react)/redesign/MobileShell.tsx
  src/app/functions/server/l10n.ts
  src/app/functions/server/mockL10n.ts
Labels: Review: XS

#3198 Scale all fonts down one notch on small screens
  src/app/tokens.scss
Labels: Review: XS

#3213 Import translations from l10n repository (2023-07-11)
  locales/trs/email-strings.ftl
Labels: l10n

#3231 Import translations from l10n repository (2023-07-24)
  locales/cs/data-classes.ftl
  locales/cy/data-classes.ftl
  locales/de/data-classes.ftl
  locales/el/app.ftl
  locales/el/landing.ftl
  locales/es-AR/data-classes.ftl
  locales/fr/app.ftl
  locales/fr/data-classes.ftl
  locales/hu/data-classes.ftl
  locales/id/data-classes.ftl
  locales/it/data-classes.ftl
  locales/pt-BR/data-classes.ftl
  locales/ru/data-classes.ftl
  locales/sl/data-classes.ftl
  locales/tr/add-email.ftl
  locales/tr/exposure-scan.ftl
  locales/zh-TW/data-classes.ftl
Labels: l10n

#3248 Import translations from l10n repository (2023-07-25)
  locales/de/data-classes.ftl
  locales/en-GB/data-classes.ftl
  locales/es-AR/data-classes.ftl
  locales/fi/data-classes.ftl
  locales/sk/data-classes.ftl
Labels: l10n

#3201 MNTOR-1692 Resolution Flow: Data Broker Results
  locales-pending/fix.ftl
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/automatic-remove/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/dataBrokerProfiles.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/start-free-scan/images/city-scape.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/start-free-scan/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/images/icon-question-mark.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/fix.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/content-background.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/icon-arrow-left.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/icon-arrow-right.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/icon-check-mark.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/icon-close.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/step-counter-data-broker-profiles.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/step-counter-done.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/step-counter-high-risk.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/step-counter-leaked-passwords.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/images/step-counter-security-recommendations.svg
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/layout.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/leaked-passwords/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/security-recommendations/page.tsx
  src/app/components/client/DataBrokerProfiles.module.scss
  src/app/components/client/DataBrokerProfiles.tsx
  src/app/components/client/FixNavigation.module.scss
  src/app/components/client/FixNavigation.tsx
  src/app/components/client/assets/step-counter-data-broker-profiles.svg
  src/app/components/client/assets/step-counter-done.svg
  src/app/components/client/assets/step-counter-high-risk.svg
  src/app/components/client/assets/step-counter-leaked-passwords.svg
  src/app/components/client/assets/step-counter-security-recommendations.svg
  src/app/components/server/button.module.scss
  src/app/tokens.scss
Labels: Review: M

#3254 Import translations from l10n repository (2023-07-26)
  locales/es-CL/data-classes.ftl
  locales/es-ES/data-classes.ftl
Labels: l10n

#3256 Import translations from l10n repository (2023-07-27)
  locales/el/app.ftl
Labels: l10n

#3259 MNTOR-1809 Returning user dashboard chart
  locales-pending/premium.ftl
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
  src/app/components/client/Chart.module.scss
  src/app/components/client/Chart.tsx
  src/app/components/client/stories/ExposureCard.stories.ts
Labels: fe-blocked

#3263 Import translations from l10n repository (2023-07-28)
  locales/ia/data-classes.ftl
  locales/uk/data-classes.ftl
  locales/vi/data-classes.ftl
  locales/zh-CN/data-classes.ftl
Labels: l10n

#3267 Import translations from l10n repository (2023-07-30)
  locales/nn-NO/recommendations.ftl
  locales/nn-NO/settings.ftl
Labels: l10n
