Repository mozilla/blurts-server, pull requests merged in 2023-12, with the labels that each got.

#3820 Import translations from l10n repository (2023-12-01)
  locales/gn/app.ftl
Labels: l10n

#3812 Add plans to the landing page on wide screens
  .eslintrc.json
  locales-pending/landing-premium.ftl
  locales/en/app.ftl
  src/app/(proper_react)/redesign/(public)/LandingView.module.scss
  src/app/(proper_react)/redesign/(public)/LandingView.test.tsx
  src/app/(proper_react)/redesign/(public)/LandingView.tsx
  src/app/(proper_react)/redesign/(public)/PlansTable.module.scss
  src/app/(proper_react)/redesign/(public)/PlansTable.tsx
  src/app/components/client/BillingPeriod.module.scss
  src/app/components/client/BillingPeriod.tsx
  src/app/components/server/VisuallyHidden.module.scss
  src/app/components/server/VisuallyHidden.tsx
  src/app/components/server/button.module.scss
Labels: Review: M

#3836 Import translations from l10n repository (2023-12-04)
  locales/cs/app.ftl
  locales/cy/app.ftl
  locales/de/app.ftl
  locales/el/app.ftl
  locales/es-AR/app.ftl
  locales/fr/app.ftl
  locales/fy-NL/app.ftl
  locales/hu/app.ftl
  locales/ia/app.ftl
  locales/id/app.ftl
  locales/it/app.ftl
  locales/nl/app.ftl
  locales/pt-BR/app.ftl
  locales/pt-PT/app.ftl
  locales/sl/app.ftl
  locales/zh-CN/app.ftl
  locales/zh-TW/app.ftl
Labels: l10n

#3839 Import translations from l10n repository (2023-12-05)
  locales/en-GB/app.ftl
  locales/fi/app.ftl
  locales/ru/app.ftl
  locales/sv-SE/app.ftl
  locales/tr/app.ftl
  locales/uk/app.ftl
  locales/vi/app.ftl
Labels: l10n

#3850 Decrease padding in plan cards
  src/app/(proper_react)/redesign/(public)/PlansTable.module.scss
  src/app/(proper_react)/redesign/(public)/PlansTable.tsx
Labels: Review: XS

#3853 Import translations from l10n repository (2023-12-10)
  locales/he/add-email.ftl
Labels: l10n

#3865 Import translations from l10n repository (2023-12-11)
  locales/es-ES/app.ftl
Labels: l10n

#3873 Align on Node 20.9 everywhere
  .github/workflows/e2e_cron.yml
  .github/workflows/e2e_pr.yml
  .github/workflows/unittests.yaml
  Dockerfile
  netlify.toml
  package.json
Labels: Review: µ

#3885 Import translations from l10n repository (2023-12-15)
  locales/cs/data-classes.ftl
  locales/cy/data-classes.ftl
  locales/de/data-classes.ftl
  locales/el/data-classes.ftl
  locales/es-AR/data-classes.ftl
  locales/fr/data-classes.ftl
  locales/hu/data-classes.ftl
  locales/ia/data-classes.ftl
  locales/id/data-classes.ftl
  locales/it/data-classes.ftl
  locales/pt-PT/data-classes.ftl
  locales/sl/data-classes.ftl
  locales/vi/data-classes.ftl
  locales/zh-TW/data-classes.ftl
Labels: l10n

#3884 MNTOR-2643 - detect client env consistently, and enable debug logging…
  sentry.client.config.ts
Labels: effort-XS

#3896 Keep the ManualRemove View universal
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremiumView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/page.tsx
Labels: Review: µ

#3824 Optimize knex connection pooling for Postgres
  src/db/knexfile.js
Labels: effort-XS

#3909 Import translations from l10n repository (2023-12-19)
  locales/gn/app.ftl
  locales/gn/data-classes.ftl
Labels: l10n

#3894 Don't access the FxA settings env var client-side
  src/app/(proper_react)/redesign/(authenticated)/admin/feature-flags/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScan.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremium.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/layout.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx
  src/app/(proper_react)/redesign/MobileShell.tsx
  src/app/(proper_react)/redesign/Shell.tsx
  src/app/components/client/toolbar/Toolbar.tsx
  src/app/components/client/toolbar/UserMenu.tsx
Labels: Review: XS

#3891 Add helper function for fetching all OneRep pages
  src/app/functions/server/onerep.ts
Labels: Review: XS

#3890 Use `upgradeIntent` for upgrade CTA
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
  src/app/components/client/PremiumUpsellDialog.tsx
Labels: Review: µ

#3886 Round down the discount percentage to whole number
  src/app/(proper_react)/redesign/(public)/LandingView.test.tsx
  src/app/(proper_react)/redesign/(public)/PlansTable.tsx
Labels: Review: XS

#3905 Also subtract manually resolved brokers
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
  src/app/functions/server/dashboard.ts
Labels: Review: XS

#3912 Align story variable with name and filename
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScan.stories.tsx
Labels: Review: µ

#3915 Import translations from l10n repository (2023-12-20)
  locales/el/app.ftl
  locales/el/email-strings.ftl
  locales/el/recommendations.ftl
  locales/sl/data-classes.ftl
Labels: l10n

#3923 Add dev docs on debugging Glean
  docs/analytics.md
Labels: Review: XS

#3922 Disallow loose equality operators
  .eslintrc.json
  src/app/(proper_react)/redesign/(authenticated)/admin/feature-flags/page.tsx
Labels: Review: µ

#3933 Import translations from l10n repository (2023-12-27)
  locales/gn/landing.ftl
Labels: l10n

#3940 Use consistent name for telemetry recording
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScanView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/EnterInfo.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/GetStarted.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/View.tsx
  src/app/components/client/PremiumUpsellDialog.tsx
  src/app/hooks/__mocks__/useTelemetry.ts
  src/app/hooks/useTelemetry.ts
Labels: Review: µ
