Repository mozilla/blurts-server, pull requests merged in 2023-09, with the labels that each got.

#3353 Import translations from l10n repository (2023-09-03)
  locales/zh-CN/add-email.ftl
  locales/zh-CN/app.ftl
  locales/zh-CN/breaches.ftl
  locales/zh-CN/settings.ftl
Labels: l10n

#3354 Import translations from l10n repository (2023-09-04)
  locales/sl/app.ftl
Labels: l10n

#3355 Ensure we don't forget to pass alt text for icons
  src/app/components/server/Icons.tsx
Labels: Review: µ

#3360 Import translations from l10n repository (2023-09-05)
  locales/es-AR/app.ftl
  locales/es-AR/landing.ftl
  locales/gn/breaches.ftl
  locales/gn/recommendations.ftl
  locales/ia/app.ftl
  locales/ia/breaches.ftl
  locales/nn-NO/breaches.ftl
Labels: l10n

#3362 Timeout Playwright tests after ten minutes
  .github/workflows/playwright.yml
Labels: Review: µ

#3358 Lint for common test errors
  .eslintrc.json
  package-lock.json
  package.json
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/Onboarding.test.tsx
  src/app/components/client/toolbar/UserMenu.test.tsx
  src/app/functions/server/featureFlags.test.ts
Labels: Review: µ

#3363 Import translations from l10n repository (2023-09-06)
  locales/da/data-classes.ftl
  locales/da/exposure-scan.ftl
  locales/gn/app.ftl
  locales/gn/recommendations.ftl
  locales/sl/breaches.ftl
  locales/sl/landing.ftl
Labels: l10n

#3350 Make coverage report available on test failures
  .github/workflows/unittests.yaml
Labels: Review: µ

#3368 Remove `buttonType` prop from <Button>
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx
  src/app/components/client/PremiumUpsellDialog.tsx
  src/app/components/server/Button.tsx
  src/app/components/server/stories/Button.stories.ts
Labels: Review: µ

#3370 Import translations from l10n repository (2023-09-07)
  locales/gn/app.ftl
  locales/gn/data-classes.ftl
  locales/sl/breaches.ftl
  locales/sl/recommendations.ftl
Labels: l10n

#3359 Split ExposureCard into Breach and Broker cards
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
  src/app/components/client/ExposureCard.tsx
  src/app/components/client/stories/ExposureCard.stories.ts
  src/app/components/server/BreachLogo.module.css
  src/app/components/server/BreachLogo.module.scss
  src/app/components/server/BreachLogo.test.tsx
  src/app/components/server/BreachLogo.tsx
  src/app/components/server/StatusPill.tsx
  src/utils/parse.js
  src/utils/parse.test.ts
Labels: Review: S

#3375 Loosen up CSP in dev mode
  src/middleware.ts
Labels: Review: µ

#3372 Explicitly verify in CI that the build succeeds
  .circleci/config.yml
Labels: Review: µ

#3381 Import translations from l10n repository (2023-09-08)
  locales/gn/breaches.ftl
  locales/gn/exposure-scan.ftl
Labels: l10n

#3373 Add type for the onerep_profiles table
  src/db/tables/onerep_profiles.ts
  src/knex-tables.d.ts
Labels: Review: XS

#3388 Import translations from l10n repository (2023-09-10)
  locales/en-CA/add-email.ftl
  locales/en-CA/app.ftl
  locales/en-CA/breaches.ftl
  locales/en-CA/data-classes.ftl
  locales/en-CA/exposure-scan.ftl
  locales/en-CA/landing.ftl
  locales/en-CA/recommendations.ftl
  locales/en-CA/settings.ftl
  locales/gn/app.ftl
Labels: l10n

#3395 Import translations from l10n repository (2023-09-12)
  locales/gn/app.ftl
  locales/gn/breaches.ftl
  locales/gn/exposure-scan.ftl
  locales/gn/recommendations.ftl
Labels: l10n

#3403 Import translations from l10n repository (2023-09-14)
  locales/sk/app.ftl
Labels: l10n

#3415 Import translations from l10n repository (2023-09-17)
  locales/gn/app.ftl
  locales/gn/breaches.ftl
  locales/gn/data-classes.ftl
  locales/gn/recommendations.ftl
  locales/zh-CN/data-classes.ftl
  locales/zh-CN/exposure-scan.ftl
Labels: l10n

#3422 Import translations from l10n repository (2023-09-18)
  locales/el/app.ftl
  locales/zh-CN/exposure-scan.ftl
  locales/zh-CN/landing.ftl
Labels: l10n

#3432 Remove re-use of CSS Modules across components
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/start-free-scan/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/page.tsx
  src/app/components/server/Button.tsx
Labels: Review: µ

#3442 Enable Premium features on Netlify
  netlify.toml
Labels: Review: µ

#3444 Stop gating Premium behind an env var
  .env-dist
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/remove/page.tsx
  src/app/(proper_react)/redesign/MobileShell.tsx
  src/app/components/client/toolbar/Toolbar.tsx
Labels: Review: µ

#3453 Don't run Playwright tests for Dependabot PRs
  .github/workflows/playwright.yml
Labels: Review: µ

#3454 Import translations from l10n repository (2023-09-25)
  locales/it/app.ftl
Labels: l10n

#3467 Import translations from l10n repository (2023-09-26)
  locales/gn/app.ftl
  locales/gn/bento.ftl
  locales/gn/breaches.ftl
  locales/gn/data-classes.ftl
  locales/gn/recommendations.ftl
  locales/gn/settings.ftl
Labels: l10n

#3475 Import translations from l10n repository (2023-09-27)
  locales/gn/data-classes.ftl
  locales/nb-NO/recommendations.ftl
Labels: l10n

#3469 Add story for the manual broker resolution view
  .storybook/preview.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/01c.ManualRemove.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/page.tsx
Labels: Review: XS

#3480 Avoid error about undefined `navigator`
  src/app/(proper_react)/redesign/GaScript.tsx
Labels: Review: µ

#3481 Import translations from l10n repository (2023-09-28)
  locales/nb-NO/recommendations.ftl
Labels: l10n
