Repository mozilla/blurts-server, pull requests merged in 2023-05, with the labels that each got.

#3020 Fix issue where Relay icon was outside of email input
  src/client/css/partials/landing.css
Labels: Review: µ

#3029 Add note on running Redis locally
  README.md
Labels: Review: µ

#3045 Fix MNTOR-1598 - Add wrapper to input form on homepage breach scan
  src/client/css/partials/landing.css
  src/views/partials/landing.js
Labels: Review: XS

#3060 Make Next-Auth work with FxA
  src/app/api/auth/[...nextauth]/route.ts
Labels: Review: XS

#3049 Port breach-detail page to Next.js
  public/images/recommendation-icons/avoid-address.svg
  public/images/recommendation-icons/avoid-personal-info.svg
  public/images/recommendation-icons/avoid-sharing-phone.svg
  public/images/recommendation-icons/change-password.svg
  public/images/recommendation-icons/dont-reuse-pwds.svg
  public/images/recommendation-icons/masked-email.svg
  public/images/recommendation-icons/monitor-bank.svg
  public/images/recommendation-icons/monitor-credit-cards.svg
  public/images/recommendation-icons/review-credit.svg
  public/images/recommendation-icons/set-2FA.svg
  public/images/recommendation-icons/store-safe-place.svg
  public/images/recommendation-icons/strengthen-pin-security.svg
  public/images/recommendation-icons/unique-answers.svg
  public/images/recommendation-icons/unique-strong-pwds.svg
  public/images/recommendation-icons/update-passwords.svg
  public/images/recommendation-icons/update-regularly.svg
  public/images/recommendation-icons/use-mask-IP-service.svg
  public/images/recommendation-icons/use-mask-location-service.svg
  src/app/(nextjs_migration)/(guest)/breach-details/[breachName]/page.tsx
  src/utils/recommendations.js
  src/views/partials/breachDetail.js
Labels: Review: S

#3066 Make mozlog work with Next.js
  package-lock.json
  package.json
  patches/intel+1.2.0.patch
  src/app/api/auth/[...nextauth]/route.ts
  src/customTypes.d.ts
  src/utils/log.js
Labels: Review: XS

#3077 Don't show error when everything was OK
  src/client/js/partials/breaches.js
Labels: Review: µ

#3089 Add a redirect from /security-tips for Next.js
  next.config.js
Labels: Review: µ

#3086 Add the app shell for the React-based website
  pendingTranslations.ftl
  src/app/(proper_react)/MobileShell.module.scss
  src/app/(proper_react)/MobileShell.tsx
  src/app/(proper_react)/PageLink.tsx
  src/app/(proper_react)/components/ControlsWrapper.module.scss
  src/app/(proper_react)/components/ControlsWrapper.tsx
  src/app/(proper_react)/layout.module.scss
  src/app/(proper_react)/layout.tsx
  src/app/(proper_react)/redesign/(authenticated)/layout.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx
  src/app/(proper_react)/test/page.tsx
  src/app/components/client/UserMenu.tsx
  src/app/components/server/Icons.tsx
  src/app/tokens.scss
Labels: Review: S
