Repository mozilla/blurts-server, pull requests merged in 2023-10, with the labels that each got.

#3484 Add docs on Jira iupdate after stage deploy
  docs/release_process.md
Labels: Review: µ

#3503 Fix Next-Auth types
  src/app/api/utils/auth.ts
  src/next-auth.d.ts
Labels: Review: XS

#3502 Import translations from l10n repository (2023-10-05)
  locales/hu/data-classes.ftl
Labels: l10n

#3512 Import translations from l10n repository (2023-10-06)
  locales/ko/app.ftl
  locales/ko/breaches.ftl
Labels: l10n

#3485 Make scan resolution skip link work
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/FixView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/start-free-scan/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/[type]/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/highRiskBreachData.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/getUserDashboardState.tsx
  src/app/functions/server/getRelevantGuidedSteps.ts
Labels: Review: XS

#3513 Import translations from l10n repository (2023-10-08)
  locales/gn/app.ftl
  locales/gn/landing.ftl
  locales/gn/recommendations.ftl
Labels: l10n

#3521 Remove dependency `node-mocks-http`
  package-lock.json
  package.json
Labels: Review: µ

#3535 Import translations from l10n repository (2023-10-11)
  locales/gn/data-classes.ftl
Labels: l10n

#3552 Import translations from l10n repository (2023-10-12)
  locales/gn/app.ftl
Labels: l10n

#3526 Change Firefox Accounts to Mozilla Accounts
  README.md
  locales-pending/premium.ftl
  locales/en/app.ftl
  locales/en/settings.ftl
  src/app/(nextjs_migration)/(authenticated)/user/layout.tsx
  src/app/(nextjs_migration)/(authenticated)/user/settings/page.tsx
  src/app/(nextjs_migration)/components/client/UserMenu.tsx
  src/app/api/utils/auth.ts
  src/app/components/client/toolbar/UserMenu.test.tsx
  src/db/tables/featureFlags.ts
  src/e2e/specs/breachResolution.spec.ts
Labels: Review: µ

#3563 Remove Helmet dependency
  package-lock.json
  package.json
  src/app.js
Labels: Review: µ

#3567 Remove nodemon dependency
  package-lock.json
  package.json
Labels: Review: µ

#3557 Group more Dependabot updates
  .github/dependabot.yml
Labels: Review: µ

#3573 Fix Dependabot config file
  .github/dependabot.yml
Labels: Review: µ

#3583 Import translations from l10n repository (2023-10-16)
  locales/ca/data-classes.ftl
  locales/cy/app.ftl
  locales/cy/settings.ftl
  locales/de/app.ftl
  locales/de/settings.ftl
  locales/es-AR/app.ftl
  locales/es-AR/settings.ftl
  locales/fi/app.ftl
  locales/fi/settings.ftl
  locales/fr/app.ftl
  locales/fr/settings.ftl
  locales/hu/app.ftl
  locales/hu/settings.ftl
  locales/id/app.ftl
  locales/id/settings.ftl
  locales/it/app.ftl
  locales/it/settings.ftl
  locales/sl/app.ftl
  locales/sl/settings.ftl
  locales/sq/app.ftl
  locales/sq/breaches.ftl
  locales/sq/exposure-scan.ftl
  locales/zh-TW/app.ftl
  locales/zh-TW/settings.ftl
Labels: l10n

#3571 Link to brokers/breached sites in a new tab
  src/app/components/client/ExposureCard.tsx
Labels: Review: µ

#3587 Import translations from l10n repository (2023-10-17)
  locales/cy/app.ftl
  locales/cy/settings.ftl
  locales/es-AR/settings.ftl
  locales/gn/app.ftl
  locales/gn/settings.ftl
  locales/nl/app.ftl
  locales/nl/settings.ftl
  locales/pt-BR/app.ftl
  locales/pt-BR/settings.ftl
  locales/ru/app.ftl
  locales/ru/settings.ftl
  locales/sk/add-email.ftl
  locales/sk/app.ftl
  locales/sk/breaches.ftl
  locales/sk/data-classes.ftl
  locales/sk/email-strings.ftl
  locales/sk/exposure-scan.ftl
  locales/sk/landing.ftl
  locales/sk/recommendations.ftl
  locales/sk/settings.ftl
  locales/sl/app.ftl
  locales/sq/add-email.ftl
  locales/sq/app.ftl
  locales/sq/data-classes.ftl
  locales/sq/exposure-scan.ftl
  locales/sq/settings.ftl
  locales/sv-SE/app.ftl
  locales/sv-SE/settings.ftl
  locales/vi/app.ftl
  locales/vi/settings.ftl
  locales/zh-CN/app.ftl
  locales/zh-CN/settings.ftl
Labels: l10n

#3586 Add upgrade link to manual scan text
  locales-pending/fix.ftl
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx
Labels: Review: µ

#3592 Import translations from l10n repository (2023-10-18)
  locales/el/app.ftl
  locales/el/settings.ftl
  locales/en-GB/app.ftl
  locales/en-GB/settings.ftl
  locales/es-CL/app.ftl
  locales/es-CL/settings.ftl
  locales/uk/app.ftl
  locales/uk/settings.ftl
Labels: l10n

#3593 Remove duplicate CSP statements
  src/middleware.ts
Labels: Review: µ

#3619 Import translations from l10n repository (2023-10-19)
  locales/cs/app.ftl
  locales/cs/settings.ftl
  locales/de/settings.ftl
  locales/es-CL/settings.ftl
  locales/fr/settings.ftl
  locales/it/settings.ftl
  locales/nl/settings.ftl
  locales/pt-BR/settings.ftl
  locales/zh-TW/settings.ftl
Labels: l10n

#3629 Import translations from l10n repository (2023-10-22)
  locales/cs/settings.ftl
  locales/cy/settings.ftl
  locales/el/settings.ftl
  locales/en-GB/settings.ftl
  locales/es-AR/settings.ftl
  locales/fi/settings.ftl
  locales/fy-NL/app.ftl
  locales/fy-NL/settings.ftl
  locales/hu/settings.ftl
  locales/ia/app.ftl
  locales/ia/settings.ftl
  locales/ru/settings.ftl
  locales/sv-SE/settings.ftl
  locales/tr/app.ftl
  locales/uk/settings.ftl
  locales/zh-CN/settings.ftl
Labels: l10n

#3637 Import translations from l10n repository (2023-10-23)
  locales/id/settings.ftl
  locales/sk/landing.ftl
  locales/sk/settings.ftl
  locales/sl/settings.ftl
Labels: l10n

#3597 MNTOR-2374 - do not redirect from new flow to front page on error
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/page.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/dashboard/subscribed/page.tsx
Labels: effort-XS

#3647 Do not assign to read-only property
  src/app/functions/server/logging.ts
Labels: Review: XS

#3658 Import translations from l10n repository (2023-10-26)
  locales/sq/breaches.ftl
  locales/sq/settings.ftl
  locales/tr/settings.ftl
Labels: l10n

#3664 Import translations from l10n repository (2023-10-27)
  locales/sl/settings.ftl
Labels: l10n

#3670 Import translations from l10n repository (2023-10-29)
  locales/en-CA/app.ftl
  locales/en-CA/settings.ftl
Labels: l10n

#3672 Import translations from l10n repository (2023-10-30)
  locales/gn/app.ftl
  locales/gn/settings.ftl
Labels: l10n

#3682 Import translations from l10n repository (2023-10-31)
  locales/gn/app.ftl
Labels: l10n
