Repository mozilla/blurts-server, pull requests merged in 2023-06, with the labels that each got.

#3090 Port unsubscribe-monthly page to Next.js
  src/app/(nextjs_migration)/(guest)/user/unsubscribe-monthly/page.tsx
Labels: Review: XS

#3104 Import translations from l10n repository (2023-06-06)
  locales/cs/app.ftl
  locales/cy/app.ftl
  locales/de/app.ftl
  locales/en-GB/app.ftl
  locales/es-AR/app.ftl
  locales/es-CL/app.ftl
  locales/es-ES/app.ftl
  locales/es-ES/exposure-scan.ftl
  locales/es-ES/landing.ftl
  locales/es-ES/settings.ftl
  locales/fi/app.ftl
  locales/fr/app.ftl
  locales/fr/settings.ftl
  locales/gn/app.ftl
  locales/gn/breaches.ftl
  locales/gn/landing.ftl
  locales/gn/recommendations.ftl
  locales/gn/settings.ftl
  locales/hu/app.ftl
  locales/ia/app.ftl
  locales/id/app.ftl
  locales/id/breaches.ftl
  locales/id/data-classes.ftl
  locales/id/email-strings.ftl
  locales/id/exposure-scan.ftl
  locales/id/landing.ftl
  locales/id/recommendations.ftl
  locales/it/app.ftl
  locales/nl/app.ftl
  locales/nn-NO/add-email.ftl
  locales/nn-NO/app.ftl
  locales/nn-NO/exposure-scan.ftl
  locales/nn-NO/landing.ftl
  locales/nn-NO/settings.ftl
  locales/pt-BR/app.ftl
  locales/ru/data-classes.ftl
  locales/sk/app.ftl
  locales/sl/app.ftl
  locales/sl/breaches.ftl
  locales/sv-SE/app.ftl
  locales/tr/app.ftl
  locales/uk/app.ftl
  locales/vi/app.ftl
  locales/zh-CN/app.ftl
  locales/zh-TW/app.ftl
  locales/zh-TW/settings.ftl
Labels: l10n

#3107 Import translations from l10n repository (2023-06-07)
  locales/fy-NL/app.ftl
  locales/nl/app.ftl
  locales/ru/app.ftl
Labels: l10n

#3109 Fix media query not working on Safari
  .stylelintrc
  .vscode/settings.json
  src/client/css/partials/floatingBanner.css
Labels: Review: µ

#3106 Port admin pages to Next.js
  public/nextjs_migration/client/js/emailPreview.js
  src/app/(nextjs_migration)/(authenticated)/admin/emails/[template]/page.tsx
  src/app/(nextjs_migration)/(authenticated)/admin/emails/page.tsx
  src/app/(nextjs_migration)/(authenticated)/admin/layout.tsx
  src/app/(nextjs_migration)/(authenticated)/admin/page.tsx
  src/app/(nextjs_migration)/(authenticated)/admin/send-test-email/route.ts
  src/utils/email.js
  src/views/emails/email2022.js
  src/views/emails/emailBreachAlert.js
  src/views/emails/emailBreachCard.js
  src/views/emails/emailMonthlyUnresolved.js
  src/views/emails/emailSignupReport.js
  src/views/emails/emailVerify.js
Labels: Review: M

#3113 Import translations from l10n repository (2023-06-09)
  locales/el/add-email.ftl
  locales/el/app.ftl
  locales/el/settings.ftl
Labels: l10n

#3115 Import translations from l10n repository (2023-06-10)
  locales/ko/breaches.ftl
Labels: l10n

#3121 Serve images at URLs referenced by emails
  public/images/email/monitor-logo-bg-light.png
  public/images/email/monitor-logo-transparent-dark-mode.png
  public/images/email/monitor-logo-transparent.png
  public/images/email/mozilla-logo-bw.png
  public/images/email/person-at-desk.png
Labels: Review: µ

#3120 Fetch breach data and icons on heartbeat
  src/app/[slug]/route.ts
Labels: Review: XS

#3125 Store an updated subscriber in their token
  src/app/api/auth/[...nextauth]/route.ts
Labels: Review: XS

#3129 Add accessibility add-on for Storybook
  .storybook/main.ts
  package-lock.json
  package.json
Labels: Review: µ

#3136 Import translations from l10n repository (2023-06-16)
  locales/sl/app.ftl
  locales/sl/landing.ftl
  locales/sl/recommendations.ftl
Labels: l10n

#3132 Don't block responses while downloading images
  src/app/functions/server/getBreaches.ts
Labels: Review: XS

#3152 Set the base path for metadata
  src/app/layout.tsx
Labels: Review: µ

#3154 Fix HIBP link in verification email
  src/views/emails/email2022.js
Labels: Review: µ

#3162 Import translations from l10n repository (2023-06-23)
  locales/tr/data-classes.ftl
  locales/tr/settings.ftl
Labels: l10n

#3167 Add type definitions for database queries
  src/app/api/utils/email.ts
  src/app/api/v1/user/resend-email/route.ts
  src/app/transitionTypes.ts
  src/customTypes.d.ts
  src/db/tables/emailAddresses.js
  src/db/tables/subscribers.js
  src/knex-tables.d.ts
  src/next-auth.d.ts
Labels: Review: XS

#3174 Also apply Prettier to HTML files
  .lintstagedrc.js
Labels: Review: µ

#3172 Fetch company icons from S3
  next.config.js
  src/app/components/server/BreachLogo.tsx
  src/app/functions/server/getBreaches.ts
Labels: Review: XS

#3180 Import translations from l10n repository (2023-06-29)
  locales/da/add-email.ftl
  locales/da/app.ftl
  locales/da/breaches.ftl
  locales/da/exposure-scan.ftl
  locales/da/settings.ftl
Labels: l10n

#3181 Also lint pendingTranslations in CI
  .github/workflows/reference_linter.yaml
Labels: Review: µ

#3178 Don't force updates of modified_date
  src/knex-tables.d.ts
Labels: Review: µ

#3183 Import translations from l10n repository (2023-06-30)
  locales/el/app.ftl
  locales/el/exposure-scan.ftl
  locales/el/landing.ftl
  locales/el/recommendations.ftl
  locales/el/settings.ftl
  locales/gn/breaches.ftl
Labels: l10n

#3182 Use a separate DB column for the favicon URL
  src/app/components/server/BreachLogo.tsx
  src/app/functions/server/getBreaches.ts
  src/db/migrations/20230630084116_add_favicon_url_to_breach.js
  src/db/tables/breaches.js
  src/knex-tables.d.ts
  src/scripts/syncBreaches.js
  src/utils/hibp.js
Labels: Review: XS
