Repository mozilla/blurts-server, pull requests merged in 2024-07, with the labels that each got.

#4740 Import translations from l10n repository (2024-07-01)
  locales/tr/fix.ftl
Labels: l10n

#4744 Import translations from l10n repository (2024-07-02)
  locales/kab/app.ftl
  locales/kab/dashboard.ftl
  locales/kab/fix.ftl
  locales/kab/landing-all.ftl
  locales/kab/recommendations.ftl
  locales/kab/settings.ftl
Labels: l10n

#4753 Import translations from l10n repository (2024-07-04)
  locales/ko/app.ftl
  locales/ko/dashboard.ftl
Labels: l10n

#4751 Adjust CSAT banner button layout (MNTOR-3317)
  src/app/components/client/csat_survey/CsatSurveyBanner.module.scss
  src/app/components/client/csat_survey/CsatSurveyBanner.tsx
Labels: Review: µ

#4749 Add telemetry to PetitionBanner (MNTOR-3337)
  src/app/components/client/PetitionBanner.tsx
Labels: Review: XS

#4762 Import translations from l10n repository (2024-07-07)
  locales/kab/dashboard.ftl
  locales/kab/fix.ftl
Labels: l10n

#4755 Don't crash when SubPlat doesn't know a user
  src/app/functions/universal/user.ts
  src/utils/fxa.js
Labels: Review: XS

#4774 Import translations from l10n repository (2024-07-08)
  locales/es-ES/dashboard.ftl
  locales/kab/dashboard.ftl
  locales/kab/exposure-card.ftl
  locales/kab/settings.ftl
Labels: l10n

#4743 Stop recreating Animation component every render
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/CancelFlow.tsx
Labels: Review: XS

#4748 Adopt .env.local file
  .env
  .env.local.example
  .github/workflows/build.yaml
  .github/workflows/e2e_cron.yml
  .github/workflows/e2e_pr.yml
  .github/workflows/lint.yaml
  .github/workflows/unittests.yaml
  .gitignore
  Dockerfile
  Dockerfile.cloudrun
  README.md
  docs/analytics.md
  docs/dependency-updates.md
  jest.setup.ts
  netlify.toml
  package-lock.json
  package.json
  playwright.config.js
  src/app/functions/l10n/index.ts
  src/appConstants.js
  src/e2e/README.md
  src/scripts/build/getAutoCompleteLocations.js
  src/scripts/s3.js
Labels: Review: S

#4780 Import translations from l10n repository (2024-07-09)
  locales/nn-NO/app.ftl
  locales/nn-NO/breaches.ftl
  locales/nn-NO/exposure-card.ftl
  locales/nn-NO/landing-all.ftl
  locales/nn-NO/recommendations.ftl
Labels: l10n

#4783 Sort breaches by added date
  src/app/(proper_react)/(redesign)/(public)/breaches/page.tsx
Labels: Review: µ

#4782 Make sure experiment code exists during tests
  .github/workflows/unittests.yaml
  package.json
Labels: Review: µ

#4786 Import translations from l10n repository (2024-07-10)
  locales/en-CA/dashboard.ftl
  locales/nn-NO/add-email.ftl
  locales/nn-NO/breaches.ftl
  locales/nn-NO/exposure-card.ftl
  locales/nn-NO/landing-all.ftl
  locales/nn-NO/settings.ftl
Labels: l10n

#4779 Migrate "delete unverified subscribers" cron to TS
  docs/dependency-updates.md
  esbuild.cronjobs.js
  package.json
  scripts/delete-unverified-subscribers.js
  src/scripts/cronjobs/deleteUnverifiedSubscribers.ts
Labels: Review: XS

#4806 Fix Storybook
  src/appConstants.js
Labels: Review: µ

#4805 Remove ts-jest, which we're not using (yet?)
  package-lock.json
  package.json
Labels: Review: µ

#4813 Import translations from l10n repository (2024-07-16)
  locales/nn-NO/dashboard.ftl
  locales/nn-NO/landing-all.ftl
Labels: l10n

#4818 Import translations from l10n repository (2024-07-17)
  locales/kab/app.ftl
  locales/kab/breaches.ftl
  locales/kab/dashboard.ftl
  locales/kab/fix.ftl
Labels: l10n

#4811 Port breach data fetching cronjob to TS
  package.json
  src/db/tables/breaches.js
  src/scripts/cronjobs/syncBreaches.ts
  src/scripts/s3.js
Labels: Review: XS

#4814 Sort-of port update-remote-settings cron to TS
  package.json
  scripts/updatebreaches.js
  src/scripts/cronjobs/updateBreachesInRemoteSettings.ts
Labels: Review: XS

#4838 Import translations from l10n repository (2024-07-21)
  locales/cs/landing-all.ftl
  locales/cy/landing-all.ftl
  locales/de/landing-all.ftl
  locales/el/landing-all.ftl
  locales/en-GB/landing-all.ftl
  locales/es-AR/landing-all.ftl
  locales/es-CL/landing-all.ftl
  locales/fi/dashboard.ftl
  locales/fi/fix.ftl
  locales/fi/landing-all.ftl
  locales/fi/settings.ftl
  locales/fr/landing-all.ftl
  locales/hu/landing-all.ftl
  locales/ia/landing-all.ftl
  locales/id/landing-all.ftl
  locales/it/landing-all.ftl
  locales/nl/landing-all.ftl
  locales/nn-NO/breaches.ftl
  locales/pt-PT/landing-all.ftl
  locales/ru/landing-all.ftl
  locales/sl/dashboard.ftl
  locales/sl/landing-all.ftl
  locales/sv-SE/landing-all.ftl
  locales/tr/landing-all.ftl
  locales/vi/landing-all.ftl
  locales/zh-CN/landing-all.ftl
  locales/zh-TW/landing-all.ftl
Labels: l10n

#4848 Import translations from l10n repository (2024-07-22)
  locales/cs/dashboard.ftl
  locales/nl/landing-all.ftl
  locales/pt-BR/landing-all.ftl
Labels: l10n

#4827 Port breach alerts cronjob to TS
  README.md
  package.json
  src/appConstants.js
  src/db/knexfile.js
  src/scripts/cronjobs/emailBreachAlerts.test.ts
  src/scripts/cronjobs/emailBreachAlerts.ts
  src/utils/hibp.js
Labels: Review: XS

#4853 Import translations from l10n repository (2024-07-23)
  locales/cs/landing-all.ftl
  locales/cy/landing-all.ftl
  locales/de/landing-all.ftl
  locales/el/landing-all.ftl
  locales/es-AR/landing-all.ftl
  locales/fr/landing-all.ftl
  locales/fy-NL/landing-all.ftl
  locales/hu/landing-all.ftl
  locales/id/landing-all.ftl
  locales/it/landing-all.ftl
  locales/nl/landing-all.ftl
  locales/pt-PT/landing-all.ftl
  locales/ru/landing-all.ftl
  locales/sk/landing-all.ftl
  locales/sl/landing-all.ftl
  locales/sv-SE/landing-all.ftl
  locales/zh-TW/landing-all.ftl
Labels: l10n

#4858 Do not run tests of compiled cronjobs
  jest.config.cjs
Labels: Review: µ

#4860 Import translations from l10n repository (2024-07-24)
  locales/de/landing-all.ftl
  locales/es-CL/landing-all.ftl
  locales/fy-NL/landing-all.ftl
  locales/ia/landing-all.ftl
  locales/it/landing-all.ftl
  locales/nl/landing-all.ftl
  locales/sk/landing-all.ftl
  locales/zh-CN/landing-all.ftl
Labels: l10n

#4859 Restore top-level 404 pages
  src/app/(metadata)/%5F_heartbeat__/route.ts
  src/app/(metadata)/%5F_lbheartbeat__/route.ts
  src/app/(metadata)/%5F_version__/route.ts
  src/app/[slug]/route.ts
  src/e2e/specs/landing.spec.ts
Labels: Review: XS

#4864 Import translations from l10n repository (2024-07-25)
  locales/en-GB/landing-all.ftl
  locales/es-AR/landing-all.ftl
  locales/tr/landing-all.ftl
Labels: l10n

#4865 Migrate utils/hibp.js to TypeScript
  src/apiMocks/mockData.ts
  src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.tsx
  src/app/api/mock/hibp/breaches/route.ts
  src/app/api/mock/hibp/range/search/[hashPrefix]/route.ts
  src/app/api/utils/auth.ts
  src/app/components/server/BreachLogo.tsx
  src/app/functions/server/breachResolution.ts
  src/app/functions/server/getBreaches.ts
  src/app/functions/universal/breach.ts
  src/db/tables/breaches.js
  src/db/tables/emailAddresses.js
  src/knex-tables.d.ts
  src/scripts/cronjobs/emailBreachAlerts.test.ts
  src/scripts/cronjobs/emailBreachAlerts.ts
  src/scripts/cronjobs/syncBreaches.ts
  src/scripts/cronjobs/updateBreachesInRemoteSettings.ts
  src/scripts/emailUpperCaseMigration.js
  src/utils/breaches.js
  src/utils/hibp.js
  src/utils/hibp.ts
  src/utils/subscriberBreaches.test.ts
  src/utils/subscriberBreaches.ts
Labels: Review: S

#4884 Import translations from l10n repository (2024-07-29)
  locales/es-MX/app.ftl
  locales/es-MX/bento.ftl
  locales/es-MX/dashboard.ftl
  locales/es-MX/exposure-card.ftl
  locales/es-MX/fix.ftl
  locales/th/add-email.ftl
  locales/th/app.ftl
  locales/th/landing-all.ftl
Labels: l10n

#4888 Import translations from l10n repository (2024-07-30)
  locales/vi/bento.ftl
Labels: l10n
