Repository mozilla/blurts-server, pull requests merged in 2024-04, with the labels that each got.

#4387 Import translations from l10n repository (2024-04-02)
  locales/az/app.ftl
  locales/az/email-strings.ftl
  locales/azz/app.ftl
  locales/azz/bento.ftl
  locales/bg/app.ftl
  locales/bg/email-strings.ftl
  locales/hus/app.ftl
  locales/ixl/app.ftl
  locales/km/app.ftl
  locales/km/data-classes.ftl
  locales/km/email-strings.ftl
  locales/lt/app.ftl
  locales/oc/app.ftl
  locales/oc/bento.ftl
  locales/oc/data-classes.ftl
  locales/oc/email-strings.ftl
  locales/oc/recommendations.ftl
  locales/ppl/app.ftl
  locales/ppl/bento.ftl
  locales/ppl/data-classes.ftl
  locales/ppl/email-strings.ftl
  locales/tl/app.ftl
  locales/tl/bento.ftl
  locales/tl/data-classes.ftl
  locales/tl/email-strings.ftl
  locales/trs/add-email.ftl
  locales/trs/app.ftl
  locales/trs/bento.ftl
  locales/trs/breaches.ftl
  locales/trs/data-classes.ftl
  locales/trs/email-strings.ftl
  locales/yua/app.ftl
  locales/yua/bento.ftl
  locales/yua/data-classes.ftl
Labels: l10n

#4385 Exit early if we can't parse the email ID
  src/app/api/v1/user/resend-email/route.ts
Labels: Review: XS

#4389 Import translations from l10n repository (2024-04-04)
  locales/nn-NO/app.ftl
  locales/nn-NO/dashboard.ftl
  locales/nn-NO/data-classes.ftl
  locales/nn-NO/fix.ftl
  locales/nn-NO/landing-all.ftl
  locales/nn-NO/settings.ftl
Labels: l10n

#4391 Import translations from l10n repository (2024-04-07)
  locales/cak/app.ftl
  locales/cs/app.ftl
  locales/cy/app.ftl
  locales/da/app.ftl
  locales/de/app.ftl
  locales/el/app.ftl
  locales/en-CA/app.ftl
  locales/en-CA/data-classes.ftl
  locales/en-CA/exposure-card.ftl
  locales/en-CA/settings.ftl
  locales/en-GB/app.ftl
  locales/es-AR/app.ftl
  locales/es-CL/app.ftl
  locales/es-ES/app.ftl
  locales/es-MX/app.ftl
  locales/fi/app.ftl
  locales/fr/app.ftl
  locales/fy-NL/app.ftl
  locales/gn/app.ftl
  locales/hu/app.ftl
  locales/ia/app.ftl
  locales/ia/settings.ftl
  locales/id/app.ftl
  locales/it/app.ftl
  locales/kab/app.ftl
  locales/ko/app.ftl
  locales/nl/app.ftl
  locales/nn-NO/app.ftl
  locales/pt-BR/app.ftl
  locales/pt-PT/app.ftl
  locales/ru/app.ftl
  locales/sk/app.ftl
  locales/sl/app.ftl
  locales/sq/app.ftl
  locales/sv-SE/app.ftl
  locales/tr/app.ftl
  locales/uk/app.ftl
  locales/vi/app.ftl
  locales/zh-CN/app.ftl
  locales/zh-TW/app.ftl
Labels: l10n

#4403 Import translations from l10n repository (2024-04-09)
  locales/nn-NO/fix.ftl
Labels: l10n

#4405 Only show cancellation link if deletion is hidden
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/View.tsx
Labels: Review: µ

#4402 MNTOR-2931 - initialize Glean after logging setup, for auto pageload …
  src/app/hooks/useGlean.ts
Labels: effort-XS

#4406 Import translations from l10n repository (2024-04-10)
  locales/cs/dashboard.ftl
  locales/cy/dashboard.ftl
  locales/de/dashboard.ftl
  locales/el/dashboard.ftl
  locales/es-AR/dashboard.ftl
  locales/es-CL/dashboard.ftl
  locales/fr/dashboard.ftl
  locales/hu/dashboard.ftl
  locales/id/dashboard.ftl
  locales/it/dashboard.ftl
  locales/nl/dashboard.ftl
  locales/pt-PT/dashboard.ftl
  locales/ru/dashboard.ftl
  locales/sl/dashboard.ftl
  locales/sv-SE/dashboard.ftl
  locales/zh-TW/dashboard.ftl
Labels: l10n

#4410 Import translations from l10n repository (2024-04-11)
  locales/cy/dashboard.ftl
  locales/de/dashboard.ftl
  locales/es-AR/dashboard.ftl
  locales/fy-NL/dashboard.ftl
  locales/pt-BR/dashboard.ftl
  locales/sk/dashboard.ftl
  locales/sv-SE/dashboard.ftl
  locales/zh-CN/dashboard.ftl
Labels: l10n

#4411 Import translations from l10n repository (2024-04-12)
  locales/en-GB/dashboard.ftl
  locales/es-CL/dashboard.ftl
  locales/ia/dashboard.ftl
  locales/ia/settings.ftl
Labels: l10n

#4416 Import translations from l10n repository (2024-04-17)
  locales/gn/dashboard.ftl
  locales/gn/exposure-card.ftl
  locales/gn/fix.ftl
  locales/hu/dashboard.ftl
  locales/uk/dashboard.ftl
Labels: l10n

#4417 Import translations from l10n repository (2024-04-18)
  locales/ia/exposure-card.ftl
  locales/ia/settings.ftl
Labels: l10n

#4418 Import translations from l10n repository (2024-04-20)
  locales/cs/dashboard.ftl
  locales/el/dashboard.ftl
  locales/uk/dashboard.ftl
  locales/uk/data-classes.ftl
  locales/uk/exposure-card.ftl
  locales/uk/settings.ftl
Labels: l10n

#4432 Import translations from l10n repository (2024-04-23)
  locales/uk/dashboard.ftl
Labels: l10n

#4437 Import translations from l10n repository (2024-04-24)
  locales/vi/dashboard.ftl
Labels: l10n

#4444 Fix dev script never running
  package.json
Labels: Review: µ

#4446 Fix: location data is relative to root
  src/scripts/build/getAutoCompleteLocations.js
Labels: Review: µ

#4449 Import translations from l10n repository (2024-04-26)
  locales/da/dashboard.ftl
  locales/tr/settings.ftl
  locales/uk/add-email.ftl
  locales/uk/app.ftl
  locales/uk/email-strings.ftl
  locales/uk/exposure-card.ftl
  locales/uk/settings.ftl
Labels: l10n

#4450 Support a `local` channel for local development
  config/nimbus.yaml
  src/app/functions/server/getExperiments.ts
  src/scripts/build/nimbusTypes.js
Labels: Review: XS

#4463 Always build experiment data before npm run dev
  package.json
Labels: Review: µ
