Repository mozilla/blurts-server, pull requests merged in 2024-02, with the labels that each got.

#4133 Import translations from l10n repository (2024-02-01)
  locales/hu/fix.ftl
  locales/hu/landing-all.ftl
Labels: l10n

#4129 Add a "Contact us" link to the user menu
  locales-pending/dashboard-premium.ftl
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
  src/app/components/client/toolbar/UserMenu.tsx
  src/app/components/client/toolbar/images/menu-icon-contact.svg
  src/constants.ts
Labels: Review: XS

#4123 Mark new scan results as in progress for Plus users
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/View.tsx
Labels: Review: XS

#4132 Fix not detecting users without scans
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-premium/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/page.tsx
  src/app/api/v1/admin/users/[primarySha1]/route.ts
  src/app/api/v1/user/welcome-scan/progress/route.ts
  src/db/tables/onerep_scans.ts
  src/db/tables/subscribers.js
Labels: Review: XS

#4141 Import translations from l10n repository (2024-02-03)
  locales/fr/dashboard.ftl
  locales/sl/dashboard.ftl
  locales/sl/exposure-card.ftl
Labels: l10n

#4142 Import translations from l10n repository (2024-02-04)
  locales/ja/add-email.ftl
  locales/ja/app.ftl
  locales/ja/bento.ftl
  locales/ja/breaches.ftl
  locales/ja/fix.ftl
  locales/ja/landing.ftl
  locales/ja/settings.ftl
  locales/tr/dashboard.ftl
  locales/tr/exposure-scan.ftl
  locales/tr/fix.ftl
  locales/tr/recommendations.ftl
Labels: l10n

#4151 Import translations from l10n repository (2024-02-05)
  locales/tr/dashboard.ftl
Labels: l10n

#4160 Add a nonce to the analytics script
  src/app/components/client/GoogleAnalyticsWorkaround.tsx
  src/app/layout.tsx
Labels: Review: XS

#4157 Use correct Privacy Policy link in welcome dialog
  src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/EnterInfo.tsx
Labels: Review: µ

#4156 Import translations from l10n repository (2024-02-08)
  locales/kab/settings.ftl
  locales/th/add-email.ftl
  locales/th/bento.ftl
  locales/th/breaches.ftl
  locales/th/settings.ftl
  locales/tr/dashboard.ftl
  locales/tr/exposure-scan.ftl
  locales/tr/fix.ftl
  locales/tr/landing-all.ftl
  locales/tr/landing.ftl
Labels: l10n

#4154 Change `premium` in URL to `plus`
  next.config.js
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.stories.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.test.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlusView.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/welcomeToPlus.module.scss
Labels: Review: XS

#4181 Import translations from l10n repository (2024-02-09)
  locales/cs/dashboard.ftl
  locales/cs/exposure-card.ftl
  locales/el/fix.ftl
Labels: l10n

#4171 Determine landing image language based on lang
  src/app/(proper_react)/(redesign)/(public)/WalkthroughImages.tsx
Labels: Review: µ

#4191 Import translations from l10n repository (2024-02-11)
  locales/cs/app.ftl
  locales/kab/add-email.ftl
  locales/kab/app.ftl
Labels: l10n

#4182 Deprecate useGa
  src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/FindExposures.tsx
  src/app/components/client/GoogleAnalyticsWorkaround.tsx
  src/app/components/client/UpsellBadge.tsx
  src/app/hooks/useGa.test.tsx
  src/app/hooks/useGa.ts
  src/app/hooks/useTelemetry.ts
  src/app/layout.tsx
Labels: Review: XS

#4201 `getSubscriberByFxaUid` and `getSubscriberByEmail` can return undefined
  src/app/api/utils/auth.ts
  src/app/api/utils/email.ts
  src/app/api/v1/admin/users/[primarySha1]/route.ts
  src/app/api/v1/fxa-rp-events/route.ts
  src/app/api/v1/user/breaches/bulk-resolve/route.ts
  src/app/api/v1/user/breaches/route.ts
  src/app/api/v1/user/email/route.ts
  src/app/api/v1/user/remove-email/route.ts
  src/app/api/v1/user/resend-email/route.ts
  src/app/api/v1/user/update-comm-option/route.ts
  src/app/api/v1/user/welcome-scan/create/route.ts
  src/app/api/v1/user/welcome-scan/progress/route.ts
  src/app/api/v1/user/welcome-scan/result/route.ts
  src/app/deprecated/(authenticated)/user/breaches/breaches.d.ts
  src/app/functions/server/changeSubscription.ts
  src/app/functions/server/getSubscriberEmails.ts
  src/app/functions/server/getUserBreaches.ts
  src/db/tables/onerep_scans.ts
  src/db/tables/subscribers.js
  src/knex-tables.d.ts
  src/utils/subscriberBreaches.ts
Labels: Review: XS

#4204 Import translations from l10n repository (2024-02-13)
  locales/cs/app.ftl
  locales/cy/app.ftl
  locales/de/app.ftl
  locales/el/app.ftl
  locales/es-AR/app.ftl
  locales/fr/app.ftl
  locales/hu/app.ftl
  locales/id/app.ftl
  locales/it/app.ftl
  locales/nl/app.ftl
  locales/pt-PT/app.ftl
  locales/ru/app.ftl
  locales/sl/app.ftl
  locales/sv-SE/app.ftl
  locales/zh-TW/app.ftl
Labels: l10n

#4208 Import translations from l10n repository (2024-02-14)
  locales/cy/app.ftl
  locales/en-GB/app.ftl
  locales/pt-BR/app.ftl
  locales/vi/app.ftl
Labels: l10n

#4071 Remove "execute" permission from Metropolis fonts
  src/app/fonts/Metropolis/Metropolis-Bold.woff2
  src/app/fonts/Metropolis/Metropolis-Medium.woff2
  src/app/fonts/Metropolis/Metropolis-SemiBold.woff2
Labels: Review: µ

#4213 Import translations from l10n repository (2024-02-15)
  locales/da/app.ftl
  locales/es-CL/app.ftl
  locales/sk/app.ftl
Labels: l10n

#4216 Import translations from l10n repository (2024-02-19)
  locales/es-ES/app.ftl
  locales/fy-NL/app.ftl
  locales/ia/app.ftl
  locales/sl/app.ftl
  locales/sl/fix.ftl
  locales/sl/landing-all.ftl
  locales/sq/app.ftl
  locales/sq/fix.ftl
  locales/sq/landing-all.ftl
  locales/tr/app.ftl
  locales/zh-CN/app.ftl
Labels: l10n

#4200 Center-align label in hero image
  src/app/(proper_react)/(redesign)/(public)/HeroImage.tsx
Labels: Review: µ

#4232 Import translations from l10n repository (2024-02-21)
  locales/cs/app.ftl
  locales/cy/app.ftl
  locales/de/app.ftl
  locales/el/app.ftl
  locales/es-AR/app.ftl
  locales/es-CL/app.ftl
  locales/fr/app.ftl
  locales/fy-NL/app.ftl
  locales/hu/app.ftl
  locales/id/app.ftl
  locales/it/app.ftl
  locales/nl/app.ftl
  locales/pt-PT/app.ftl
  locales/ru/app.ftl
  locales/sl/app.ftl
  locales/sv-SE/app.ftl
  locales/uk/add-email.ftl
  locales/uk/app.ftl
  locales/uk/bento.ftl
  locales/uk/landing-all.ftl
  locales/uk/settings.ftl
  locales/vi/app.ftl
  locales/zh-CN/app.ftl
  locales/zh-TW/app.ftl
Labels: l10n

#4214 Enforce authOptions with getServerSession wrapper
  .eslintrc.json
  src/app/(migration_remnants)/(guest)/layout.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/admin/dev/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/layout.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/layout.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/actions.ts
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/[[...slug]]/page.tsx
  src/app/(proper_react)/(redesign)/(public)/page.tsx
  src/app/(proper_react)/layout.tsx
  src/app/api/v1/admin/feature-flags/[flagId]/route.ts
  src/app/api/v1/admin/feature-flags/route.ts
  src/app/api/v1/admin/users/[primarySha1]/route.ts
  src/app/api/v1/user/breaches/bulk-resolve/route.ts
  src/app/api/v1/user/scan-result/[onerepScanResultId]/resolution/route.ts
  src/app/api/v1/user/welcome-scan/create/route.ts
  src/app/api/v1/user/welcome-scan/progress/route.ts
  src/app/api/v1/user/welcome-scan/result/route.ts
  src/app/deprecated/(authenticated)/admin/emails/[template]/page.tsx
  src/app/deprecated/(authenticated)/admin/emails/page.tsx
  src/app/deprecated/(authenticated)/admin/layout.tsx
  src/app/deprecated/(authenticated)/user/breaches/page.tsx
  src/app/deprecated/(authenticated)/user/layout.tsx
  src/app/deprecated/(authenticated)/user/settings/page.tsx
  src/app/deprecated/(guest)/layout.tsx
  src/app/functions/server/getServerSession.ts
  src/app/layout.tsx
Labels: Review: XS

#4238 Import translations from l10n repository (2024-02-22)
  locales/en-GB/app.ftl
  locales/ia/app.ftl
  locales/nb-NO/data-classes.ftl
  locales/pt-BR/app.ftl
  locales/uk/app.ftl
  locales/uk/exposure-card.ftl
  locales/uk/landing-all.ftl
Labels: l10n

#4233 Also check for updates of Actions
  .github/dependabot.yml
Labels: Review: µ

#4273 Import translations from l10n repository (2024-02-27)
  locales/tr/app.ftl
Labels: l10n

#4275 Import translations from l10n repository (2024-02-28)
  locales/uk/dashboard.ftl
Labels: l10n

#4231 add global client error handling per Sentry docs
  src/app/global-error.js
Labels: effort-XS

#4282 Import translations from l10n repository (2024-02-29)
  locales/sq/app.ftl
Labels: l10n
