Repository mozilla/blurts-server, pull requests merged in 2024-03, with the labels that each got.

#4286 Import translations from l10n repository (2024-03-01)
  locales/tr/app.ftl
Labels: l10n

#4272 Add a story to test the progress bar
  src/app/components/client/stories/ProgressBar.stories.tsx
Labels: Review: XS

#4302 Import translations from l10n repository (2024-03-05)
  locales/cs/exposure-card.ftl
  locales/cs/settings.ftl
  locales/cy/exposure-card.ftl
  locales/cy/landing-all.ftl
  locales/cy/settings.ftl
  locales/de/exposure-card.ftl
  locales/de/settings.ftl
  locales/el/exposure-card.ftl
  locales/el/settings.ftl
  locales/es-AR/exposure-card.ftl
  locales/es-AR/settings.ftl
  locales/fr/exposure-card.ftl
  locales/fr/settings.ftl
  locales/hu/exposure-card.ftl
  locales/hu/settings.ftl
  locales/id/exposure-card.ftl
  locales/id/settings.ftl
  locales/it/exposure-card.ftl
  locales/it/settings.ftl
  locales/nl/exposure-card.ftl
  locales/nl/settings.ftl
  locales/pt-BR/settings.ftl
  locales/pt-PT/exposure-card.ftl
  locales/pt-PT/settings.ftl
  locales/ru/exposure-card.ftl
  locales/ru/settings.ftl
  locales/sl/exposure-card.ftl
  locales/sl/settings.ftl
  locales/sv-SE/exposure-card.ftl
  locales/sv-SE/settings.ftl
  locales/uk/dashboard.ftl
  locales/uk/landing-all.ftl
  locales/zh-TW/exposure-card.ftl
  locales/zh-TW/settings.ftl
Labels: l10n

#4306 Import translations from l10n repository (2024-03-06)
  locales/de/exposure-card.ftl
  locales/de/settings.ftl
  locales/es-AR/settings.ftl
  locales/pt-BR/settings.ftl
  locales/sl/data-classes.ftl
  locales/sq/exposure-card.ftl
  locales/sq/settings.ftl
  locales/sv-SE/exposure-card.ftl
  locales/sv-SE/settings.ftl
  locales/vi/exposure-card.ftl
  locales/vi/settings.ftl
Labels: l10n

#4305 More arbitrary c8 ignores
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/ResolutionContainer.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/ResolutionContent.tsx
  src/app/components/client/Button.tsx
  src/app/components/client/FixNavigation.tsx
  src/app/components/client/ScanResultCard.tsx
  src/app/components/client/UpsellBadge.tsx
  src/app/components/client/toolbar/UserMenu.tsx
  src/app/functions/server/dashboard.ts
  src/app/functions/server/getRelevantGuidedSteps.ts
  src/app/functions/universal/guidedExperienceBreaches.ts
  src/app/hooks/useLocalDismissal.ts
Labels: Review: µ

#4307 Merge changes from 2024.03.01.01 hotfix release back into main
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/EmailListing.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/View.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/actions.ts
  src/app/deprecated/(authenticated)/user/settings/page.tsx
  src/app/functions/server/getUserBreaches.ts
  src/app/functions/server/sanitizeEmailRow.ts
  src/db/tables/emailAddresses.js
  src/utils/breaches.js
  src/utils/subscriberBreaches.ts
Labels: Review: µ

#4308 Import translations from l10n repository (2024-03-07)
  locales/en-GB/exposure-card.ftl
  locales/en-GB/settings.ftl
  locales/es-AR/exposure-card.ftl
  locales/es-AR/settings.ftl
  locales/hu/exposure-card.ftl
  locales/hu/settings.ftl
  locales/pt-BR/exposure-card.ftl
  locales/pt-BR/settings.ftl
  locales/pt-PT/app.ftl
  locales/pt-PT/exposure-card.ftl
  locales/pt-PT/settings.ftl
  locales/tr/settings.ftl
Labels: l10n

#4313 Import translations from l10n repository (2024-03-08)
  locales/es-CL/exposure-card.ftl
  locales/es-CL/settings.ftl
  locales/gn/app.ftl
  locales/gn/settings.ftl
  locales/uk/dashboard.ftl
Labels: l10n

#4326 Import translations from l10n repository (2024-03-11)
  locales/da/exposure-card.ftl
  locales/da/settings.ftl
  locales/es-ES/exposure-card.ftl
  locales/es-ES/settings.ftl
  locales/sk/exposure-card.ftl
  locales/sk/settings.ftl
  locales/tr/settings.ftl
Labels: l10n

#4328 Import translations from l10n repository (2024-03-12)
  locales/cs/exposure-card.ftl
  locales/cy/exposure-card.ftl
  locales/cy/settings.ftl
  locales/da/settings.ftl
Labels: l10n

#4331 Update description for the BVD breach
  src/apiMocks/mockData.ts
  src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailView.stories.tsx
  src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailView.tsx
  src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailsView.test.tsx
  src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.stories.tsx
  src/utils/recommendations.js
Labels: Review: XS

#4339 Import translations from l10n repository (2024-03-17)
  locales/gn/dashboard.ftl
  locales/gn/fix.ftl
  locales/zh-TW/settings.ftl
Labels: l10n

#4203 Move aria-live into <Button>
  src/app/components/client/Button.test.tsx
  src/app/components/client/Button.tsx
Labels: Review: XS

#4346 Only (re)send verification emails for current user
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/actions.ts
  src/app/api/utils/email.ts
  src/db/tables/emailAddresses.js
Labels: Review: XS

#4335 Only run glean-probe-scraper if we modified metrics
  .github/workflows/glean-probe-scraper.yml
Labels: Review: µ

#4347 Add citizenship-statuses data breach label
  locales/en/data-classes.ftl
Labels: Review: µ

#4349 Import translations from l10n repository (2024-03-19)
  locales/gn/app.ftl
  locales/gn/dashboard.ftl
  locales/gn/exposure-card.ftl
  locales/gn/fix.ftl
Labels: l10n

#4352 Import translations from l10n repository (2024-03-20)
  locales/zh-TW/settings.ftl
Labels: l10n

#4354 Import translations from l10n repository (2024-03-21)
  locales/cs/data-classes.ftl
  locales/cs/exposure-card.ftl
  locales/cs/settings.ftl
  locales/de/data-classes.ftl
  locales/de/exposure-card.ftl
  locales/de/settings.ftl
  locales/el/data-classes.ftl
  locales/el/exposure-card.ftl
  locales/el/settings.ftl
  locales/fr/data-classes.ftl
  locales/fr/exposure-card.ftl
  locales/fr/settings.ftl
  locales/hu/data-classes.ftl
  locales/hu/exposure-card.ftl
  locales/hu/settings.ftl
  locales/id/data-classes.ftl
  locales/id/exposure-card.ftl
  locales/id/settings.ftl
  locales/it/app.ftl
  locales/it/data-classes.ftl
  locales/it/exposure-card.ftl
  locales/it/settings.ftl
  locales/nl/data-classes.ftl
  locales/nl/exposure-card.ftl
  locales/nl/settings.ftl
  locales/ru/data-classes.ftl
  locales/ru/exposure-card.ftl
  locales/ru/settings.ftl
  locales/zh-TW/data-classes.ftl
  locales/zh-TW/exposure-card.ftl
  locales/zh-TW/settings.ftl
Labels: l10n

#4358 Import translations from l10n repository (2024-03-22)
  locales/de/exposure-card.ftl
  locales/es-AR/data-classes.ftl
  locales/es-AR/settings.ftl
  locales/es-CL/data-classes.ftl
  locales/es-CL/exposure-card.ftl
  locales/es-CL/settings.ftl
  locales/pt-BR/data-classes.ftl
  locales/pt-BR/exposure-card.ftl
  locales/pt-BR/settings.ftl
  locales/sk/data-classes.ftl
  locales/sk/exposure-card.ftl
  locales/sk/settings.ftl
  locales/sv-SE/data-classes.ftl
  locales/sv-SE/exposure-card.ftl
  locales/sv-SE/settings.ftl
  locales/tr/data-classes.ftl
  locales/tr/exposure-card.ftl
  locales/tr/settings.ftl
  locales/zh-CN/data-classes.ftl
  locales/zh-CN/exposure-card.ftl
  locales/zh-CN/settings.ftl
Labels: l10n

#4360 Import translations from l10n repository (2024-03-23)
  locales/en-GB/data-classes.ftl
  locales/en-GB/exposure-card.ftl
  locales/en-GB/settings.ftl
  locales/fy-NL/data-classes.ftl
  locales/fy-NL/exposure-card.ftl
  locales/fy-NL/settings.ftl
  locales/nl/exposure-card.ftl
  locales/sq/data-classes.ftl
  locales/sq/exposure-card.ftl
  locales/sq/settings.ftl
  locales/vi/data-classes.ftl
  locales/vi/exposure-card.ftl
  locales/vi/settings.ftl
Labels: l10n

#4361 Import translations from l10n repository (2024-03-24)
  locales/es-AR/exposure-card.ftl
Labels: l10n

#4351 Remove some more unused code and dependencies
  package-lock.json
  package.json
  patches/intel+1.2.0.patch
  public/vercel.svg
  scripts/is-coveralls-configured.js
  src/app/api/v1/scan/route.ts
  src/app/functions/server/changeSubscription.ts
  src/customTypes.d.ts
  src/scripts/webp.sh
  src/utils/fxa.js
  src/utils/redisMock.js
  src/utils/stringHelpers.js
  tsconfig.json
Labels: Review: XS

#4371 Import translations from l10n repository (2024-03-27)
  locales/da/data-classes.ftl
  locales/da/exposure-card.ftl
  locales/da/settings.ftl
Labels: l10n

#4372 Import translations from l10n repository (2024-03-28)
  locales/cy/data-classes.ftl
  locales/cy/exposure-card.ftl
  locales/cy/settings.ftl
  locales/hu/exposure-card.ftl
  locales/hu/settings.ftl
Labels: l10n

#4373 Import translations from l10n repository (2024-03-29)
  locales/el/exposure-card.ftl
  locales/el/settings.ftl
  locales/fi/data-classes.ftl
  locales/fi/exposure-card.ftl
  locales/fi/settings.ftl
Labels: l10n

#4375 Import translations from l10n repository (2024-03-30)
  locales/cs/data-classes.ftl
  locales/cs/exposure-card.ftl
  locales/cs/settings.ftl
Labels: l10n
