Repository mozilla/blurts-server, pull requests merged in 2024-01, with the labels that each got.

#3941 Import translations from l10n repository (2023-12-31)
  locales/pt-PT/data-classes.ftl
  locales/pt-PT/landing.ftl
  locales/pt-PT/settings.ftl
Labels: l10n

#3956 Import translations from l10n repository (2024-01-03)
  locales/ru/breaches.ftl
Labels: l10n

#3958 Hide "exposure type" filter when there's just one
  locales-pending/dashboard-premium.ftl
  locales/en/dashboard.ftl
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
  src/app/components/client/ExposuresFilter.tsx
Labels: Review: XS

#3936 Port settings page to proper React
  .storybook/preview.tsx
  docs/test-coverage.md
  locales/en/add-email.ftl
  locales/en/app.ftl
  locales/en/settings.ftl
  src/TestComponentWrapper.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/AlertAddressForm.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/AlertAddressForm.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/EmailAddressAdder.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/EmailAddressAdder.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/EmailListing.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/EmailListing.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/View.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/actions.ts
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/images/AddEmailDialogIllustration.svg
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/page.tsx
  src/app/(proper_react)/redesign/MobileShell.tsx
  src/app/(proper_react)/redesign/Shell.tsx
  src/app/api/utils/auth.ts
  src/app/api/v1/user/remove-email/route.ts
  src/app/api/v1/user/update-comm-option/route.ts
  src/app/components/server/Icons.tsx
  src/db/tables/emailAddresses.js
Labels: Review: L

#3964 No dash in "in progress"
  locales-pending/dashboard-premium.ftl
Labels: Review: µ

#3973 Import translations from l10n repository (2024-01-05)
  locales/en-GB/add-email.ftl
  locales/en-GB/app.ftl
  locales/en-GB/bento.ftl
  locales/en-GB/dashboard.ftl
  locales/es-AR/fix.ftl
  locales/es-AR/settings.ftl
  locales/fr/app.ftl
  locales/gn/add-email.ftl
  locales/gn/app.ftl
  locales/gn/bento.ftl
  locales/gn/dashboard.ftl
  locales/gn/exposure-card.ftl
  locales/gn/fix.ftl
  locales/gn/landing-all.ftl
  locales/gn/settings.ftl
  locales/hu/fix.ftl
  locales/ia/app.ftl
  locales/ia/dashboard.ftl
  locales/it/app.ftl
  locales/it/dashboard.ftl
  locales/it/data-classes.ftl
  locales/it/exposure-card.ftl
  locales/it/fix.ftl
  locales/it/landing-all.ftl
  locales/zh-CN/add-email.ftl
  locales/zh-CN/app.ftl
  locales/zh-CN/breaches.ftl
  locales/zh-CN/data-classes.ftl
  locales/zh-CN/email-strings.ftl
  locales/zh-CN/exposure-scan.ftl
  locales/zh-CN/landing.ftl
  locales/zh-TW/app.ftl
  locales/zh-TW/dashboard.ftl
  locales/zh-TW/exposure-card.ftl
  locales/zh-TW/fix.ftl
  locales/zh-TW/landing-all.ftl
Labels: l10n

#3960 Also suppress non-error logs in tests
  jest.setup.ts
  src/app/hooks/useGa.ts
  src/scripts/emailBreachAlerts.test.js
  src/utils/email.test.js
Labels: Review: XS

#3976 Import translations from l10n repository (2024-01-07)
  locales/ia/add-email.ftl
  locales/ia/app.ftl
  locales/ia/breaches.ftl
  locales/ia/dashboard.ftl
  locales/ia/email-strings.ftl
  locales/ia/fix.ftl
  locales/ia/landing-all.ftl
  locales/ia/settings.ftl
  locales/kab/app.ftl
  locales/ru/app.ftl
  locales/ru/dashboard.ftl
  locales/ru/fix.ftl
  locales/sk/app.ftl
  locales/sq/app.ftl
  locales/sv-SE/dashboard.ftl
  locales/sv-SE/fix.ftl
  locales/uk/app.ftl
  locales/zh-CN/app.ftl
  locales/zh-CN/bento.ftl
  locales/zh-CN/breaches.ftl
  locales/zh-CN/dashboard.ftl
  locales/zh-CN/email-strings.ftl
  locales/zh-CN/exposure-card.ftl
  locales/zh-CN/exposure-scan.ftl
  locales/zh-CN/fix.ftl
  locales/zh-CN/settings.ftl
Labels: l10n

#3962 Respect the SUPPORTED_LOCALES env var
  src/app/functions/server/l10n.ts
Labels: Review: XS

#3988 Import translations from l10n repository (2024-01-08)
  locales/cs/app.ftl
  locales/cs/settings.ftl
  locales/el/add-email.ftl
  locales/el/app.ftl
  locales/el/bento.ftl
  locales/el/dashboard.ftl
  locales/el/email-strings.ftl
  locales/el/exposure-card.ftl
  locales/el/fix.ftl
  locales/el/landing-all.ftl
  locales/fy-NL/add-email.ftl
  locales/fy-NL/app.ftl
  locales/gn/dashboard.ftl
  locales/gn/exposure-card.ftl
  locales/gn/fix.ftl
  locales/hu/exposure-card.ftl
  locales/ia/fix.ftl
  locales/nl/dashboard.ftl
  locales/nl/exposure-card.ftl
  locales/nl/fix.ftl
  locales/nl/landing-all.ftl
  locales/nl/settings.ftl
  locales/sk/dashboard.ftl
  locales/sk/exposure-card.ftl
  locales/sk/fix.ftl
  locales/sk/landing-all.ftl
  locales/sv-SE/app.ftl
  locales/sv-SE/dashboard.ftl
  locales/sv-SE/exposure-card.ftl
  locales/sv-SE/fix.ftl
  locales/sv-SE/landing-all.ftl
Labels: l10n

#3972 Allow loading Storybook in other locales
  .storybook/preview.tsx
  src/TestComponentWrapper.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScan.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremium.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
  src/app/(proper_react)/redesign/(public)/LandingView.stories.tsx
  src/app/functions/server/__mocks__/l10n.ts
  src/app/functions/server/mockL10n.ts
Labels: Review: XS

#3991 Remove direct c8 dependency
  package-lock.json
  package.json
Labels: Review: µ

#3995 Add strings for the rebrand announcement banner
  locales/en/app.ftl
Labels: Review: µ

#3996 Import translations from l10n repository (2024-01-09)
  locales/el/dashboard.ftl
  locales/el/exposure-card.ftl
  locales/el/fix.ftl
  locales/el/landing-all.ftl
  locales/es-CL/add-email.ftl
  locales/es-CL/app.ftl
  locales/es-CL/bento.ftl
  locales/es-CL/dashboard.ftl
  locales/fr/landing-all.ftl
  locales/fy-NL/app.ftl
  locales/fy-NL/bento.ftl
  locales/fy-NL/dashboard.ftl
  locales/fy-NL/exposure-card.ftl
  locales/fy-NL/fix.ftl
  locales/fy-NL/landing-all.ftl
  locales/fy-NL/settings.ftl
  locales/gn/app.ftl
  locales/gn/fix.ftl
  locales/gn/landing-all.ftl
  locales/hu/app.ftl
  locales/hu/dashboard.ftl
  locales/hu/email-strings.ftl
  locales/hu/fix.ftl
  locales/nl/exposure-card.ftl
  locales/nl/fix.ftl
  locales/nl/landing-all.ftl
  locales/pt-BR/dashboard.ftl
  locales/sk/dashboard.ftl
  locales/sk/exposure-card.ftl
  locales/sk/fix.ftl
  locales/sk/landing-all.ftl
  locales/sk/landing.ftl
  locales/vi/dashboard.ftl
  locales/zh-CN/add-email.ftl
  locales/zh-CN/app.ftl
  locales/zh-CN/breaches.ftl
  locales/zh-CN/dashboard.ftl
  locales/zh-CN/data-classes.ftl
  locales/zh-CN/email-strings.ftl
  locales/zh-CN/exposure-scan.ftl
  locales/zh-CN/landing.ftl
  locales/zh-CN/recommendations.ftl
  locales/zh-CN/settings.ftl
  locales/zh-TW/add-email.ftl
  locales/zh-TW/app.ftl
  locales/zh-TW/breaches.ftl
  locales/zh-TW/dashboard.ftl
  locales/zh-TW/email-strings.ftl
  locales/zh-TW/exposure-card.ftl
  locales/zh-TW/exposure-scan.ftl
  locales/zh-TW/landing-all.ftl
  locales/zh-TW/landing.ftl
Labels: l10n

#3992 Fix Guided Resolution step 1b. in Storybook
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx
Labels: Review: µ

#4002 Update broker scan date
  .env-dist
Labels: Review: µ

#4014 Import translations from l10n repository (2024-01-12)
  locales/de/app.ftl
  locales/de/dashboard.ftl
  locales/en-CA/add-email.ftl
  locales/en-CA/app.ftl
  locales/en-CA/bento.ftl
  locales/en-CA/dashboard.ftl
  locales/en-CA/exposure-card.ftl
  locales/en-CA/fix.ftl
  locales/en-CA/landing-all.ftl
  locales/en-CA/settings.ftl
  locales/es-AR/app.ftl
  locales/es-AR/dashboard.ftl
  locales/fi/exposure-card.ftl
  locales/fi/fix.ftl
  locales/fi/landing-all.ftl
  locales/gn/dashboard.ftl
  locales/gn/fix.ftl
  locales/gn/landing-all.ftl
  locales/ia/app.ftl
  locales/ia/dashboard.ftl
  locales/ia/exposure-card.ftl
  locales/ia/fix.ftl
  locales/ia/landing-all.ftl
  locales/nb-NO/add-email.ftl
  locales/nl/dashboard.ftl
  locales/pt-BR/app.ftl
  locales/pt-BR/dashboard.ftl
  locales/pt-BR/landing-all.ftl
  locales/ru/app.ftl
  locales/ru/dashboard.ftl
  locales/sq/app.ftl
  locales/sv-SE/dashboard.ftl
  locales/tr/app.ftl
  locales/tr/dashboard.ftl
  locales/tr/fix.ftl
  locales/tr/landing-all.ftl
Labels: l10n

#4000 Add link to cancellation page in settings
  locales-pending/settings-premium.ftl
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/View.module.scss
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/page.tsx
Labels: Review: XS

#4012 Count interactions with guided flow nav buttons
  docs/analytics.md
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/FixView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.test.tsx
Labels: Review: µ

#4013 Ignore DoNotTrack when running locally
  src/app/hooks/useGlean.ts
Labels: Review: µ

#4005 Remove NEXT_PUBLIC env vars by constants
  .env-dist
  src/app/(nextjs_migration)/(authenticated)/user/breaches/page.tsx
  src/app/(nextjs_migration)/(authenticated)/user/settings/page.tsx
  src/app/(nextjs_migration)/components/server/AddEmailDialog.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemoveView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScanView.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/AboutBrokersIcon.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/EmailAddressAdder.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/View.tsx
  src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/actions.ts
  src/app/(proper_react)/redesign/(authenticated)/user/welcome/[[...slug]]/page.tsx
  src/app/(proper_react)/redesign/(public)/Faq.tsx
  src/app/(proper_react)/redesign/(public)/PlansTable.tsx
  src/app/(proper_react)/redesign/(public)/ScanLimit.tsx
  src/app/(proper_react)/redesign/Footer.tsx
  src/app/(proper_react)/redesign/GaScript.tsx
  src/app/api/v1/user/email/route.ts
  src/app/components/client/Chart.tsx
  src/app/components/client/ExposuresFilterExplainer.tsx
  src/app/components/client/SubscriberWaitlistDialog.tsx
  src/app/components/client/UpsellDialog.tsx
  src/app/components/client/toolbar/UserMenu.tsx
  src/app/hooks/useGa.ts
  src/app/layout.tsx
  src/constants.ts
Labels: Review: XS

#4019 Import translations from l10n repository (2024-01-13)
  locales/fi/app.ftl
  locales/fi/dashboard.ftl
  locales/ia/app.ftl
  locales/ia/dashboard.ftl
  locales/pt-BR/dashboard.ftl
  locales/pt-BR/fix.ftl
  locales/pt-BR/landing-all.ftl
  locales/sl/bento.ftl
  locales/sl/fix.ftl
  locales/tr/fix.ftl
Labels: l10n

#4020 Import translations from l10n repository (2024-01-14)
  locales/cs/dashboard.ftl
  locales/en-GB/app.ftl
  locales/en-GB/dashboard.ftl
  locales/en-GB/landing-all.ftl
  locales/fi/fix.ftl
  locales/fi/landing-all.ftl
  locales/ko/add-email.ftl
  locales/ko/app.ftl
Labels: l10n

#4032 Import translations from l10n repository (2024-01-15)
  locales/es-ES/add-email.ftl
  locales/es-ES/bento.ftl
  locales/es-ES/exposure-card.ftl
  locales/es-ES/settings.ftl
  locales/ia/dashboard.ftl
  locales/sk/add-email.ftl
  locales/sk/app.ftl
  locales/sk/dashboard.ftl
  locales/sk/landing-all.ftl
  locales/sk/settings.ftl
Labels: l10n

#4034 Import translations from l10n repository (2024-01-16)
  locales/hu/dashboard.ftl
  locales/sk/dashboard.ftl
  locales/sk/data-classes.ftl
  locales/sk/fix.ftl
  locales/sq/add-email.ftl
  locales/sq/app.ftl
  locales/sq/bento.ftl
  locales/sq/dashboard.ftl
  locales/sq/exposure-card.ftl
  locales/sq/fix.ftl
  locales/sq/landing-all.ftl
  locales/sq/settings.ftl
  locales/tr/fix.ftl
  locales/tr/landing-all.ftl
Labels: l10n

#4015 Fix autoprefixer warnings
  src/app/(proper_react)/redesign/(public)/PlansTable.module.scss
  src/app/components/client/ExposureCard.module.scss
  src/client/css/global.css
  src/client/css/partials/landing.css
Labels: Review: µ

#4041 Import translations from l10n repository (2024-01-18)
  locales/fr/dashboard.ftl
  locales/gn/fix.ftl
  locales/hu/fix.ftl
  locales/sk/breaches.ftl
  locales/sk/fix.ftl
Labels: l10n

#4044 Pass OneRep sandbox API key to end-to-end tests
  .github/workflows/e2e_cron.yml
  .github/workflows/e2e_pr.yml
Labels: Review: µ

#4049 Somewhat more resilient selectors for auth page
  src/e2e/pages/authPage.ts
Labels: Review: XS

#4048 Import translations from l10n repository (2024-01-19)
  locales/es-CL/app.ftl
  locales/fr/exposure-card.ftl
  locales/fr/fix.ftl
  locales/fr/landing-all.ftl
Labels: l10n

#4050 Make setup headed when any browser is
  src/e2e/global-setup.ts
Labels: Review: XS

#4051 Refine setup for VSCode users
  .vscode/extensions.json
  .vscode/settings.json
Labels: Review: µ

#4053 Import translations from l10n repository (2024-01-21)
  locales/cs/add-email.ftl
  locales/cs/app.ftl
  locales/cs/bento.ftl
  locales/cs/dashboard.ftl
  locales/fi/fix.ftl
  locales/he/app.ftl
  locales/ia/dashboard.ftl
  locales/ia/exposure-card.ftl
  locales/ia/fix.ftl
  locales/sl/dashboard.ftl
  locales/sl/exposure-card.ftl
  locales/sl/landing-all.ftl
Labels: l10n

#4067 Import translations from l10n repository (2024-01-22)
  locales/cs/dashboard.ftl
  locales/cs/exposure-card.ftl
  locales/cs/fix.ftl
  locales/cs/landing-all.ftl
  locales/es-ES/app.ftl
  locales/es-ES/dashboard.ftl
  locales/es-ES/fix.ftl
  locales/es-ES/landing-all.ftl
  locales/fr/dashboard.ftl
  locales/fr/fix.ftl
  locales/fr/landing-all.ftl
  locales/ia/fix.ftl
  locales/pt-PT/add-email.ftl
  locales/pt-PT/app.ftl
  locales/pt-PT/dashboard.ftl
  locales/pt-PT/exposure-card.ftl
  locales/pt-PT/fix.ftl
  locales/sl/add-email.ftl
  locales/sl/app.ftl
  locales/sl/dashboard.ftl
  locales/sl/settings.ftl
  locales/tr/dashboard.ftl
  locales/tr/exposure-card.ftl
  locales/tr/fix.ftl
  locales/tr/landing-all.ftl
Labels: l10n

#4072 Import translations from l10n repository (2024-01-23)
  locales/fr/dashboard.ftl
  locales/fr/exposure-card.ftl
  locales/fr/fix.ftl
  locales/fr/landing-all.ftl
  locales/he/app.ftl
  locales/kab/app.ftl
  locales/kab/bento.ftl
  locales/kab/breaches.ftl
  locales/kab/dashboard.ftl
  locales/pt-PT/fix.ftl
Labels: l10n

#4073 Split build step into separate CI job
  .circleci/config.yml
  .github/workflows/build.yaml
Labels: Review: XS

#4074 Only show cancellation link if the user has Plus
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/View.tsx
Labels: Review: XS

#4084 Import translations from l10n repository (2024-01-25)
  locales/es-CL/fix.ftl
  locales/fi/dashboard.ftl
  locales/fi/fix.ftl
  locales/fi/landing-all.ftl
  locales/fr/app.ftl
  locales/fr/exposure-scan.ftl
  locales/nn-NO/data-classes.ftl
  locales/tr/app.ftl
  locales/tr/dashboard.ftl
  locales/tr/fix.ftl
  locales/tr/landing-all.ftl
  locales/tr/landing.ftl
  locales/tr/settings.ftl
Labels: l10n

#4081 Refresh breaches after resolving some
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/SecurityRecommendationsLayout.tsx
Labels: Review: XS

#4087 Fix invalid rollback
  src/db/migrations/20240111101826_subscriber_email_cascade_delete.js
Labels: Review: µ

#4091 Update OneRep API base URL
  .env-dist
Labels: Review: µ

#4090 Import translations from l10n repository (2024-01-26)
  locales/da/add-email.ftl
  locales/da/app.ftl
  locales/da/bento.ftl
  locales/da/data-classes.ftl
  locales/es-CL/dashboard.ftl
  locales/es-CL/fix.ftl
  locales/kab/app.ftl
  locales/kab/dashboard.ftl
  locales/kab/exposure-card.ftl
  locales/kab/fix.ftl
  locales/kab/landing-all.ftl
  locales/kab/landing.ftl
  locales/kab/settings.ftl
  locales/nn-NO/app.ftl
  locales/pt-PT/fix.ftl
  locales/tr/dashboard.ftl
Labels: l10n

#4099 Import translations from l10n repository (2024-01-28)
  locales/cs/dashboard.ftl
  locales/cs/exposure-card.ftl
  locales/cs/fix.ftl
  locales/cs/landing-all.ftl
  locales/da/dashboard.ftl
  locales/da/exposure-card.ftl
  locales/da/fix.ftl
  locales/da/landing-all.ftl
  locales/da/settings.ftl
  locales/en-CA/fix.ftl
  locales/en-CA/landing-all.ftl
  locales/fi/dashboard.ftl
  locales/fi/fix.ftl
  locales/he/app.ftl
  locales/he/email-strings.ftl
  locales/pt-PT/breaches.ftl
  locales/pt-PT/fix.ftl
  locales/pt-PT/landing-all.ftl
  locales/th/add-email.ftl
  locales/th/app.ftl
Labels: l10n

#4102 Import translations from l10n repository (2024-01-29)
  locales/da/app.ftl
  locales/da/exposure-card.ftl
  locales/da/fix.ftl
  locales/da/landing-all.ftl
  locales/es-ES/fix.ftl
  locales/fi/fix.ftl
  locales/uk/app.ftl
Labels: l10n

#4096 Allow linking directly to the FAQ section
  src/app/(proper_react)/(redesign)/(public)/Faq.tsx
Labels: Review: µ

#4120 Import translations from l10n repository (2024-01-30)
  locales/cs/fix.ftl
  locales/cs/landing-all.ftl
  locales/tr/breaches.ftl
  locales/tr/dashboard.ftl
  locales/tr/exposure-scan.ftl
Labels: l10n

#4125 Import translations from l10n repository (2024-01-31)
  locales/fr/landing-all.ftl
  locales/hu/fix.ftl
Labels: l10n
