Repository mozilla/blurts-server, pull requests merged in 2024-05, with the labels that each got.

#4462 Do not import feature flag module from subscribers
  src/db/tables/featureFlags.ts
  src/db/tables/subscribers.js
  src/utils/email.test.js
Labels: Review: XS

#4464 Import translations from l10n repository (2024-05-01)
  locales/sq/dashboard.ftl
Labels: l10n

#4466 Import translations from l10n repository (2024-05-02)
  locales/cs/settings.ftl
  locales/cy/settings.ftl
  locales/de/settings.ftl
  locales/el/settings.ftl
  locales/es-AR/settings.ftl
  locales/fr/settings.ftl
  locales/fy-NL/settings.ftl
  locales/hu/settings.ftl
  locales/id/settings.ftl
  locales/it/settings.ftl
  locales/kab/add-email.ftl
  locales/nl/settings.ftl
  locales/pt-BR/data-classes.ftl
  locales/pt-BR/settings.ftl
  locales/pt-PT/settings.ftl
  locales/ru/settings.ftl
  locales/sl/settings.ftl
  locales/sq/settings.ftl
  locales/sv-SE/settings.ftl
  locales/zh-TW/settings.ftl
Labels: l10n

#4469 Add npm scripts to run cron jobs
  package.json
Labels: Review: µ

#4474 Import translations from l10n repository (2024-05-03)
  locales/de/settings.ftl
  locales/el/settings.ftl
  locales/en-GB/settings.ftl
  locales/es-CL/settings.ftl
  locales/fr/settings.ftl
  locales/gn/settings.ftl
  locales/ia/settings.ftl
  locales/ru/settings.ftl
  locales/sk/settings.ftl
  locales/sv-SE/settings.ftl
  locales/tr/settings.ftl
  locales/uk/settings.ftl
Labels: l10n

#4476 Fix paths to FTL files from cron job l10n loading
  src/app/functions/l10n/cronjobs.ts
Labels: Review: µ

#4478 Import translations from l10n repository (2024-05-05)
  locales/cs/settings.ftl
  locales/da/settings.ftl
  locales/en-CA/settings.ftl
  locales/es-AR/settings.ftl
  locales/gn/fix.ftl
  locales/gn/settings.ftl
  locales/ja/add-email.ftl
  locales/ja/app.ftl
  locales/ja/bento.ftl
  locales/ja/fix.ftl
  locales/ja/settings.ftl
  locales/nn-NO/settings.ftl
  locales/vi/settings.ftl
Labels: l10n

#4487 Import translations from l10n repository (2024-05-06)
  locales/cs/settings.ftl
  locales/de/settings.ftl
  locales/el/settings.ftl
  locales/es-ES/settings.ftl
  locales/fr/settings.ftl
  locales/hu/settings.ftl
  locales/id/settings.ftl
  locales/it/settings.ftl
  locales/ja/app.ftl
  locales/ja/breaches.ftl
  locales/ja/dashboard.ftl
  locales/ja/data-classes.ftl
  locales/ja/exposure-card.ftl
  locales/nl/settings.ftl
  locales/pt-BR/settings.ftl
  locales/ru/settings.ftl
  locales/zh-TW/settings.ftl
Labels: l10n

#4488 Fix cron jobs not finding FTL files
  src/app/functions/l10n/cronjobs.ts
Labels: Review: XS

#4473 Add npm scripts for remaining cron jobs
  package.json
Labels: Review: XS

#4495 Import translations from l10n repository (2024-05-07)
  locales/de/settings.ftl
  locales/en-GB/settings.ftl
  locales/es-CL/settings.ftl
  locales/sk/settings.ftl
  locales/sv-SE/settings.ftl
Labels: l10n

#4494 Don't send new users the monthly activity email
  src/db/tables/subscribers.js
Labels: Review: XS

#4511 Import translations from l10n repository (2024-05-08)
  locales/es-AR/settings.ftl
  locales/hu/settings.ftl
  locales/ia/settings.ftl
  locales/kab/settings.ftl
  locales/pt-PT/dashboard.ftl
  locales/pt-PT/data-classes.ftl
  locales/pt-PT/exposure-card.ftl
  locales/pt-PT/settings.ftl
  locales/vi/settings.ftl
Labels: l10n

#4513 Import translations from l10n repository (2024-05-10)
  locales/cy/settings.ftl
  locales/gn/fix.ftl
  locales/sl/dashboard.ftl
  locales/sl/data-classes.ftl
  locales/sl/exposure-card.ftl
  locales/sl/fix.ftl
  locales/sl/landing-all.ftl
  locales/sl/settings.ftl
  locales/tr/settings.ftl
  locales/zh-CN/breaches.ftl
  locales/zh-CN/settings.ftl
Labels: l10n

#4475 Add/use dark mode versions of email images
  public/images/email/icons/question-mark-circle-purple-dark-mode.png
  public/images/email/icons/question-mark-circle-purple.png
  src/emails/templates/EmailFooter.tsx
  src/emails/templates/EmailHeader.tsx
  src/emails/templates/EmailStyles.tsx
  src/emails/templates/monthlyActivity/MonthlyActivityEmail.tsx
Labels: Review: XS

#4521 Import translations from l10n repository (2024-05-12)
  locales/cs/settings.ftl
Labels: l10n

#4530 Import translations from l10n repository (2024-05-13)
  locales/es-ES/settings.ftl
Labels: l10n

#4537 Remove dangling reference to deleted string
  src/scripts/cronjobs/monthlyActivity.tsx
Labels: Review: µ

#4550 Don't run preview deployments for Dependabot PRs
  .github/workflows/preview_deploy_gcp.yml
  .github/workflows/preview_deploy_gcp_cleanup.yml
Labels: Review: µ

#4536 Refresh stored scans before sending activity email
  src/app/functions/server/refreshStoredScanResults.ts
  src/scripts/cronjobs/monthlyActivity.tsx
Labels: Review: XS

#4552 Import translations from l10n repository (2024-05-22)
  locales/en-CA/settings.ftl
  locales/gn/fix.ftl
  locales/gn/settings.ftl
  locales/ko/app.ftl
  locales/ko/landing-all.ftl
  locales/sq/settings.ftl
  locales/tr/breaches.ftl
Labels: l10n

#4556 Delete dark mode-specific images
  public/images/email/icons/question-mark-circle-purple-dark-mode.png
  public/images/email/icons/question-mark-circle-purple.png
  public/images/email/icons/question-mark-circle-with-bg.png
  public/images/email/monitor-logo-transparent-dark-mode.png
  public/images/email/monitor-logo-transparent.png
  public/images/email/monitor-logo-with-bg.png
  src/emails/templates/EmailFooter.tsx
  src/emails/templates/EmailHeader.tsx
  src/emails/templates/EmailStyles.tsx
  src/emails/templates/boilerplate/BoilerplateEmail.tsx
  src/emails/templates/monthlyActivity/MonthlyActivityEmail.tsx
  src/emails/templates/verifyEmailAddress/VerifyEmailAddressEmail.tsx
Labels: Review: XS

#4572 List auto-removals first in monthly email
  src/emails/templates/monthlyActivity/MonthlyActivityEmail.tsx
Labels: Review: µ

#4587 use language and region for Nimbus/Cirrus
  src/app/functions/server/getExperiments.ts
Labels: effort-XS

#4551 Use useHasRenderedClientSide in l10n hook
  src/app/hooks/__mocks__/useHasRenderedClientSide.ts
  src/app/hooks/l10n.ts
Labels: Review: XS

#4579 Remove inline styles from server components
  src/app/(proper_react)/(redesign)/(public)/HeroImage.module.scss
  src/app/(proper_react)/(redesign)/(public)/HeroImage.tsx
  src/app/components/server/Icons.tsx
Labels: Review: XS
