Repository mozilla/blurts-server, pull requests merged in 2024-10, with the labels that each got.

#5130 More outdated UTM parameters
  src/emails/components/EmailDataPointCount.tsx
  src/emails/components/EmailHero.tsx
  src/emails/templates/EmailFooter.tsx
  src/emails/templates/breachAlert/BreachAlertEmail.test.tsx
  src/emails/templates/breachAlert/BreachAlertEmail.tsx
Labels: Review: µ

#5125 Import translations from l10n repository (2024-10-06)
  locales/sl/bento.ftl
  locales/sl/dashboard.ftl
  locales/sl/email-strings.ftl
  locales/sl/exposure-card.ftl
  locales/sl/fix.ftl
  locales/sl/settings.ftl
Labels: l10n

#5152 Import translations from l10n repository (2024-10-09)
  locales/ko/fix.ftl
  locales/ko/recommendations.ftl
  locales/ko/unsubscribe.ftl
Labels: l10n

#5153 Remove need to import React in cronjobs
  esbuild.cronjobs.js
  src/emails/components/BreachCard.tsx
  src/emails/components/EmailBanner.tsx
  src/emails/components/EmailDataPointCount.tsx
  src/emails/components/EmailHero.tsx
  src/emails/templates/EmailFooter.tsx
  src/emails/templates/EmailHeader.tsx
  src/emails/templates/breachAlert/BreachAlertEmail.tsx
  src/emails/templates/firstDataBrokerRemovalFixed/FirstDataBrokerRemovalFixed.tsx
  src/emails/templates/monthlyActivity/MonthlyActivityEmail.tsx
  src/emails/templates/monthlyActivity/freeUser/MonthlyActivityFreeUser.tsx
  src/emails/templates/signupReport/SignupReportEmail.tsx
  src/scripts/cronjobs/emailBreachAlerts.tsx
  src/scripts/cronjobs/firstDataBrokerRemovalFixed.tsx
  src/scripts/cronjobs/monthlyActivity.tsx
Labels: Review: µ

#5155 Add nightly testing job to report "true" coverage
  .github/workflows/unittests.yaml
Labels: Review: XS

#5181 Import translations from l10n repository (2024-10-15)
  locales/da/email-strings.ftl
  locales/da/unsubscribe.ftl
Labels: l10n

#5184 Move unsubscribe link generation into own module
  src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx
  src/app/functions/cronjobs/unsubscribeLinks.ts
  src/scripts/cronjobs/monthlyActivityFree.tsx
Labels: Review: XS

#5186 Import translations from l10n repository (2024-10-16)
  locales/da/email-strings.ftl
  locales/da/unsubscribe.ftl
Labels: l10n

#5193 Import translations from l10n repository (2024-10-17)
  locales/nn-NO/dashboard.ftl
Labels: l10n

#5208 Import translations from l10n repository (2024-10-21)
  locales/es-ES/email-strings.ftl
  locales/es-ES/unsubscribe.ftl
Labels: l10n

#5214 Skip upcoming non-LTS Node releases
  .github/dependabot.yml
Labels: Review: µ

#5202 MNTOR-3707: Push source maps to Sentry
  .github/workflows/build.yaml
Labels: Review: µ

#5216 MNTOR-3648: Also record Glean-native page load events
  src/app/components/client/PageLoadEvent.tsx
Labels: Review: µ

#5227 MNTOR-3606: Respect allowlist of disabled flag
  src/db/tables/subscribers.ts
Labels: Review: XS

#5237 Import translations from l10n repository (2024-10-25)
  locales/cs/app.ftl
  locales/cs/breaches.ftl
  locales/cy/app.ftl
  locales/cy/breaches.ftl
  locales/de/app.ftl
  locales/de/breaches.ftl
  locales/el/app.ftl
  locales/el/breaches.ftl
  locales/es-AR/app.ftl
  locales/es-AR/breaches.ftl
  locales/es-CL/app.ftl
  locales/es-CL/breaches.ftl
  locales/fr/app.ftl
  locales/fr/breaches.ftl
  locales/hu/app.ftl
  locales/hu/breaches.ftl
  locales/id/app.ftl
  locales/id/breaches.ftl
  locales/it/app.ftl
  locales/it/breaches.ftl
  locales/nl/app.ftl
  locales/nl/breaches.ftl
  locales/pt-PT/app.ftl
  locales/pt-PT/breaches.ftl
  locales/ru/app.ftl
  locales/ru/breaches.ftl
  locales/sl/app.ftl
  locales/sl/breaches.ftl
  locales/sv-SE/app.ftl
  locales/sv-SE/breaches.ftl
  locales/zh-CN/app.ftl
  locales/zh-CN/breaches.ftl
  locales/zh-TW/app.ftl
  locales/zh-TW/breaches.ftl
Labels: l10n

#5239 Import translations from l10n repository (2024-10-27)
  locales/cs/breaches.ftl
  locales/cy/app.ftl
  locales/cy/breaches.ftl
  locales/de/breaches.ftl
  locales/en-GB/app.ftl
  locales/en-GB/breaches.ftl
  locales/es-AR/breaches.ftl
  locales/hu/app.ftl
  locales/hu/breaches.ftl
  locales/ko/app.ftl
  locales/ko/breaches.ftl
  locales/sk/app.ftl
  locales/sk/breaches.ftl
  locales/sv-SE/breaches.ftl
  locales/vi/app.ftl
  locales/vi/breaches.ftl
  locales/zh-TW/breaches.ftl
Labels: l10n

#5259 Import translations from l10n repository (2024-10-29)
  locales/el/app.ftl
  locales/el/breaches.ftl
  locales/gn/app.ftl
  locales/gn/breaches.ftl
Labels: l10n

#5264 Import translations from l10n repository (2024-10-30)
  locales/vi/breaches.ftl
  locales/vi/fix.ftl
  locales/vi/recommendations.ftl
Labels: l10n

#5258 MNTOR-3494: Upload Sentry source maps by default
  next.config.js
Labels: Review: µ

#5260 Close the SMTP connection pool when done
  src/scripts/cronjobs/emailBreachAlerts.tsx
  src/scripts/cronjobs/firstDataBrokerRemovalFixed.tsx
  src/scripts/cronjobs/monthlyActivityFree.tsx
  src/scripts/cronjobs/monthlyActivityPlus.tsx
  src/utils/email.test.ts
  src/utils/email.ts
Labels: Review: XS

#5254 Only initialise LoggingWinston when used
  src/app/functions/server/glean.ts
  src/app/functions/server/logging.ts
Labels: Review: µ

#5256 Always output the coverage report
  .github/workflows/unittests.yaml
Labels: Review: µ

#5257 Use a singleton for the DB connection object
  src/db/connect.ts
  src/scripts/cronjobs/monthlyActivityFree.tsx
Labels: Review: XS

#5203 MNTOR-3711: Properly fall back to error if token doesn't match
  src/db/tables/subscriber_email_preferences.ts
Labels: Review: µ
