Repository mozilla/blurts-server, pull requests merged in 2024-08, with the labels that each got.

#4904 Import translations from l10n repository (2024-08-04)
  locales/ko/app.ftl
  locales/ko/breaches.ftl
  locales/ko/fix.ftl
Labels: l10n

#4921 Import translations from l10n repository (2024-08-06)
  locales/cs/email-strings.ftl
  locales/de/email-strings.ftl
  locales/el/email-strings.ftl
  locales/en-GB/email-strings.ftl
  locales/fr/email-strings.ftl
  locales/fy-NL/email-strings.ftl
  locales/hu/email-strings.ftl
  locales/id/email-strings.ftl
  locales/it/email-strings.ftl
  locales/nl/email-strings.ftl
  locales/zh-TW/email-strings.ftl
Labels: l10n

#4923 Use solid background colour for logo in dark mode
  public/images/email/monitor-logo-with-bg.png
  src/emails/StorybookEmailRenderer.tsx
  src/emails/templates/monthlyActivity/MonthlyActivityEmail.stories.tsx
Labels: Review: µ

#4916 Update docs on react-intersection-observer testing
  docs/dependency-updates.md
Labels: Review: µ

#4927 Remove unused monthly unresolved email template
  locales/en/email-strings.ftl
  scripts/send-email-to-unresolved-breach-subscribers.js
  src/emails/emailMonthlyUnresolved.js
  src/utils/email.js
Labels: Review: µ

#4933 Import translations from l10n repository (2024-08-09)
  locales/cs/email-strings.ftl
  locales/vi/email-strings.ftl
Labels: l10n

#4937 Import translations from l10n repository (2024-08-10)
  locales/en-CA/email-strings.ftl
  locales/es-AR/email-strings.ftl
  locales/ia/email-strings.ftl
  locales/sq/email-strings.ftl
Labels: l10n

#4938 Import translations from l10n repository (2024-08-16)
  locales/cy/email-strings.ftl
  locales/hu/email-strings.ftl
  locales/ja/add-email.ftl
  locales/ja/app.ftl
  locales/ja/bento.ftl
  locales/ja/breaches.ftl
  locales/ja/dashboard.ftl
  locales/ja/email-strings.ftl
  locales/ja/exposure-card.ftl
  locales/ja/fix.ftl
  locales/ja/landing-all.ftl
  locales/ja/recommendations.ftl
  locales/ja/settings.ftl
  locales/pt-PT/landing-all.ftl
  locales/sk/email-strings.ftl
  locales/zh-CN/email-strings.ftl
  locales/zh-TW/email-strings.ftl
Labels: l10n

#4905 Use the full width in the email header
  src/emails/templates/EmailHeader.tsx
Labels: Review: XS

#4964 Align disabled state with email validation
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/EmailAddressAdder.tsx
Labels: Review: XS

#4967 More intuitive flag behaviour
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/AddFeatureFlag.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/page.tsx
  src/app/(proper_react)/(redesign)/(public)/page.tsx
  src/db/tables/featureFlags.ts
Labels: Review: XS

#4982 Add new string for menu entry in the footer
  locales/en/app.ftl
Labels: Review: µ

#4968 Remove `SetExpectationsForUsers` flag
  locales-pending/dashboard-premium.ftl
  locales-pending/fix-premium.ftl
  locales-pending/landing-premium.ftl
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/index.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/View.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/ResolutionContainer.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.stories.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlusView.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/SecurityRecommendationsLayout.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/page.tsx
  src/app/(proper_react)/(redesign)/(public)/Faq.tsx
  src/app/(proper_react)/(redesign)/(public)/LandingView.stories.tsx
  src/app/(proper_react)/(redesign)/(public)/LandingView.tsx
  src/app/(proper_react)/(redesign)/(public)/page.tsx
  src/app/components/client/ExposuresFilterExplainer.tsx
  src/app/components/client/PercentageChart.tsx
  src/app/components/client/ProgressCard.tsx
  src/app/components/client/stories/ProgressCard.stories.ts
  src/db/tables/featureFlags.ts
Labels: Review: XS

#4971 Prevent breach cards from overflowing on mobile
  src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.module.scss
Labels: Review: XS

#4984 Rename Monthly Monitor report to *Plus report
  locales-pending/settings-premium.ftl
  locales/en/settings.ftl
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/AlertAddressForm.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
Labels: Review: XS

#4991 Import translations from l10n repository (2024-08-28)
  locales/da/app.ftl
  locales/da/dashboard.ftl
  locales/da/email-strings.ftl
  locales/da/landing-all.ftl
  locales/en-GB/app.ftl
  locales/fy-NL/app.ftl
Labels: l10n

#4994 Import translations from l10n repository (2024-08-29)
  locales/da/dashboard.ftl
  locales/vi/app.ftl
Labels: l10n
