Repository mozilla/blurts-server, pull requests merged in 2024-09, with the labels that each got.

#4999 Import translations from l10n repository (2024-09-01)
  locales/hu/data-classes.ftl
Labels: l10n

#5014 Import translations from l10n repository (2024-09-03)
  locales/uk/app.ftl
Labels: l10n

#5016 Reduce dashboard axe runs to a single one
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
Labels: Review: µ

#5021 Import translations from l10n repository (2024-09-08)
  locales/cy/landing-all.ftl
  locales/en-CA/app.ftl
  locales/th/dashboard.ftl
Labels: l10n

#5023 In the flag UI, only show flags that the code uses
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/AddFeatureFlag.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/DeleteFeatureFlag.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.tsx
  src/app/api/v1/admin/feature-flags/route.ts
  src/db/tables/featureFlags.ts
Labels: Review: XS

#5038 Only load scan results if a scan ran
  src/db/tables/onerep_scans.ts
Labels: Review: µ

#5044 Remove AppConstants
  .prettierignore
  jest.config.cjs
  jest.setup.ts
  src/app/api/utils/auth.tsx
  src/app/api/v1/fxa-rp-events/route.ts
  src/app/api/v1/user/email/route.ts
  src/app/api/v1/user/remove-email/route.ts
  src/appConstants.js
  src/db/tables/subscribers.ts
  src/envVars.ts
  src/scripts/cronjobs/updateBreachesInRemoteSettings.ts
  src/utils/dockerflow.ts
  src/utils/email.ts
  src/utils/fxa.ts
  src/utils/hibp.ts
Labels: Review: XS

#5058 Import translations from l10n repository (2024-09-16)
  locales/cs/unsubscribe.ftl
  locales/de/unsubscribe.ftl
  locales/el/unsubscribe.ftl
  locales/es-ES/app.ftl
  locales/es-ES/email-strings.ftl
  locales/es-ES/landing-all.ftl
  locales/fr/unsubscribe.ftl
  locales/hu/unsubscribe.ftl
  locales/id/unsubscribe.ftl
  locales/it/unsubscribe.ftl
  locales/nl/unsubscribe.ftl
  locales/pt-BR/unsubscribe.ftl
  locales/pt-PT/unsubscribe.ftl
  locales/zh-TW/unsubscribe.ftl
Labels: l10n

#5070 Remove localstorage.js
  src/scripts/cronjobs/emailBreachAlerts.tsx
  src/utils/localStorage.js
Labels: Review: µ

#5071 Import translations from l10n repository (2024-09-17)
  locales/de/unsubscribe.ftl
  locales/el/unsubscribe.ftl
  locales/en-GB/unsubscribe.ftl
  locales/es-AR/unsubscribe.ftl
  locales/fr/unsubscribe.ftl
  locales/fy-NL/unsubscribe.ftl
  locales/hu/unsubscribe.ftl
  locales/ia/unsubscribe.ftl
  locales/ko/breaches.ftl
  locales/ko/dashboard.ftl
  locales/ko/fix.ftl
  locales/ko/landing-all.ftl
  locales/ko/recommendations.ftl
  locales/nl/unsubscribe.ftl
  locales/ru/unsubscribe.ftl
  locales/sk/unsubscribe.ftl
  locales/sq/unsubscribe.ftl
  locales/sv-SE/unsubscribe.ftl
  locales/zh-CN/unsubscribe.ftl
Labels: l10n

#5074 Fix data loading logic on admin email page
  src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx
Labels: Review: µ

#5075 Import translations from l10n repository (2024-09-18)
  locales/cs/email-strings.ftl
  locales/cy/email-strings.ftl
  locales/de/email-strings.ftl
  locales/el/email-strings.ftl
  locales/es-AR/email-strings.ftl
  locales/fr/email-strings.ftl
  locales/fy-NL/email-strings.ftl
  locales/fy-NL/unsubscribe.ftl
  locales/hu/email-strings.ftl
  locales/id/email-strings.ftl
  locales/it/email-strings.ftl
  locales/nl/email-strings.ftl
  locales/nn-NO/dashboard.ftl
  locales/pt-PT/email-strings.ftl
  locales/ru/email-strings.ftl
  locales/sl/email-strings.ftl
  locales/sv-SE/email-strings.ftl
  locales/zh-TW/email-strings.ftl
Labels: l10n

#5073 Allow switching cronjob script without downtime
  package.json
Labels: Review: µ

#5080 Import translations from l10n repository (2024-09-19)
  locales/cs/unsubscribe.ftl
  locales/de/email-strings.ftl
  locales/de/unsubscribe.ftl
  locales/el/email-strings.ftl
  locales/el/unsubscribe.ftl
  locales/en-GB/email-strings.ftl
  locales/es-AR/email-strings.ftl
  locales/fr/email-strings.ftl
  locales/fr/unsubscribe.ftl
  locales/fy-NL/unsubscribe.ftl
  locales/gn/app.ftl
  locales/gn/email-strings.ftl
  locales/gn/landing-all.ftl
  locales/gn/unsubscribe.ftl
  locales/hu/email-strings.ftl
  locales/hu/unsubscribe.ftl
  locales/ia/email-strings.ftl
  locales/id/unsubscribe.ftl
  locales/it/unsubscribe.ftl
  locales/nl/unsubscribe.ftl
  locales/nn-NO/dashboard.ftl
  locales/nn-NO/email-strings.ftl
  locales/pt-BR/email-strings.ftl
  locales/ru/email-strings.ftl
  locales/sk/email-strings.ftl
  locales/zh-CN/email-strings.ftl
  locales/zh-CN/landing-all.ftl
  locales/zh-CN/unsubscribe.ftl
  locales/zh-TW/unsubscribe.ftl
Labels: l10n

#5079 Make sure React is in scope for email's BreachCard
  src/emails/components/BreachCard.tsx
Labels: Review: µ

#5068 MNTOR-3029 - guard against un-parseable URLs being passed to next-auth redirect
  src/app/api/utils/auth.tsx
Labels: :stop_sign: Do Not Merge

#5099 Import translations from l10n repository (2024-09-24)
  locales/es-CL/email-strings.ftl
  locales/es-CL/unsubscribe.ftl
  locales/sl/app.ftl
  locales/sl/dashboard.ftl
  locales/sl/email-strings.ftl
  locales/sl/unsubscribe.ftl
  locales/sq/email-strings.ftl
  locales/sq/unsubscribe.ftl
  locales/tr/email-strings.ftl
  locales/tr/unsubscribe.ftl
Labels: l10n

#5081 Ensure bold text for CSS-less email clients
  src/emails/templates/breachAlert/BreachAlertEmail.tsx
Labels: Review: µ

#5100 Import translations from l10n repository (2024-09-25)
  locales/cy/email-strings.ftl
  locales/cy/unsubscribe.ftl
  locales/tr/email-strings.ftl
  locales/tr/unsubscribe.ftl
Labels: l10n

#5107 Import translations from l10n repository (2024-09-29)
  locales/de/breaches.ftl
  locales/de/landing-all.ftl
  locales/de/recommendations.ftl
  locales/kab/unsubscribe.ftl
  locales/ko/app.ftl
  locales/ko/breaches.ftl
  locales/ko/dashboard.ftl
  locales/ko/data-classes.ftl
  locales/ko/email-strings.ftl
  locales/ko/exposure-card.ftl
  locales/ko/fix.ftl
  locales/ko/landing-all.ftl
  locales/ko/settings.ftl
  locales/zh-TW/app.ftl
Labels: l10n

#5103 Fix reported breach alert email medium
  src/emails/templates/breachAlert/BreachAlertEmail.tsx
Labels: Review: µ

#5109 Import translations from l10n repository (2024-09-30)
  locales/tr/unsubscribe.ftl
Labels: l10n
