Repository mozilla/blurts-server, pull requests merged in 2025-06, with the labels that each got.

#5957 Try to skip Node versions 24.x until 24.10
  .github/dependabot.yml
Labels: Review: µ

#5940 Highlight feature flags that are active in prod
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.tsx
Labels: Review: XS

#5980 Import translations from l10n repository (2025-06-24)
  locales/ml/data-classes.ftl
  locales/ml/exposure-card.ftl
  locales/ml/fix.ftl
  locales/ml/recommendations.ftl
  locales/nb-NO/app.ftl
Labels: l10n
