Repository mozilla/blurts-server, pull requests merged in 2025-03, with the labels that each got.

#5684 MNTOR-4151: Use higher-res images for the logo in emails
  public/images/email/monitor-logo-transparent.png
  public/images/email/monitor-logo-with-bg.png
Labels: Review: XS

#5682 MNTOR-3945: Add a search icon to the breach filter field
  src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.module.scss
  src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.tsx
  src/app/components/server/Icons.tsx
Labels: Review: XS

#5686 Don't shrink allowlist deletion button
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.tsx
Labels: Review: XS

#5687 Add missing values to .env.local.example
  .env.local.example
Labels: Review: µ

#5695 Log FxA error response, not "[Object object]"
  src/utils/fxa.ts
Labels: Review: µ

#5670 Import translations from l10n repository (2025-03-19)
  locales/el/email-strings.ftl
  locales/es-MX/breaches.ftl
  locales/es-MX/dashboard.ftl
  locales/es-MX/exposure-card.ftl
  locales/es-MX/fix.ftl
  locales/es-MX/landing-all.ftl
  locales/es-MX/recommendations.ftl
  locales/es-MX/settings.ftl
  locales/es-MX/unsubscribe.ftl
  locales/id/breaches.ftl
  locales/id/dashboard.ftl
  locales/id/email-strings.ftl
  locales/id/exposure-card.ftl
  locales/id/fix.ftl
  locales/id/landing-all.ftl
  locales/id/recommendations.ftl
  locales/id/settings.ftl
  locales/id/unsubscribe.ftl
  locales/ml/app.ftl
  locales/ml/settings.ftl
  locales/ml/unsubscribe.ftl
  locales/nn-NO/app.ftl
  locales/nn-NO/breaches.ftl
  locales/nn-NO/dashboard.ftl
  locales/nn-NO/email-strings.ftl
  locales/nn-NO/fix.ftl
Labels: l10n

#5734 Import translations from l10n repository (2025-03-26)
  locales/ml/add-email.ftl
  locales/ml/app.ftl
  locales/ml/bento.ftl
  locales/ml/breaches.ftl
  locales/ml/dashboard.ftl
  locales/ml/email-strings.ftl
Labels: l10n

#5736 Import translations from l10n repository (2025-03-27)
  locales/ml/data-classes.ftl
  locales/ml/recommendations.ftl
Labels: l10n

#5735 SVCSE-2596: Log how many emails we've sent at a timeout
  src/scripts/cronjobs/monthlyActivityFree.tsx
Labels: Review: µ

#5738 Import translations from l10n repository (2025-03-30)
  locales/th/breaches.ftl
  locales/th/dashboard.ftl
  locales/th/fix.ftl
Labels: l10n

#5740 Import translations from l10n repository (2025-03-31)
  locales/nn-NO/breaches.ftl
  locales/nn-NO/dashboard.ftl
  locales/nn-NO/email-strings.ftl
  locales/nn-NO/exposure-card.ftl
  locales/nn-NO/fix.ftl
  locales/nn-NO/settings.ftl
  locales/nn-NO/unsubscribe.ftl
Labels: l10n
