Repository mozilla/blurts-server, pull requests merged in 2025-01, with the labels that each got.

#5451 Import translations from l10n repository (2025-01-02)
  locales/pt-PT/fix.ftl
  locales/th/dashboard.ftl
  locales/th/data-classes.ftl
  locales/th/email-strings.ftl
  locales/th/fix.ftl
  locales/th/landing-all.ftl
  locales/th/recommendations.ftl
  locales/th/settings.ftl
  locales/th/unsubscribe.ftl
Labels: l10n

#5469 Import translations from l10n repository (2025-01-09)
  locales/da/fix.ftl
  locales/da/settings.ftl
  locales/el/add-email.ftl
  locales/el/settings.ftl
  locales/es-AR/email-strings.ftl
  locales/es-MX/add-email.ftl
  locales/es-MX/app.ftl
  locales/es-MX/bento.ftl
  locales/es-MX/breaches.ftl
  locales/es-MX/dashboard.ftl
  locales/es-MX/data-classes.ftl
  locales/es-MX/email-strings.ftl
  locales/es-MX/exposure-card.ftl
  locales/es-MX/fix.ftl
  locales/nn-NO/email-strings.ftl
Labels: l10n

#5479 MNTOR-3919: db table changes for churn email column (Part 1)
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPageRedesign.test.tsx
  src/db/migrations/20250109140803_add_churn_prevention_email_sent.js
  src/knex-tables.d.ts
  src/utils/subscriberBreaches.test.ts
Labels: Review: µ

#5496 Add modal dialog to Storybook
  src/app/components/client/stories/ModalDialog.stories.tsx
Labels: Review: XS

#5507 Undo reverts
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/[[...slug]]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/[[...slug]]/page.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/[[...slug]]/page.tsx
  src/app/(proper_react)/(redesign)/(public)/page.tsx
  src/app/api/v1/user/welcome-scan/create/route.ts
  src/app/functions/server/getExperiments.ts
  src/app/hooks/useGlean.ts
  src/app/layout.tsx
  src/contextProviders/experiments.tsx
  src/middleware.ts
  src/telemetry/metrics.yaml
Labels: :stop_sign: Do Not Merge, Review: µ

#5508 Handle both V1 and V2 of Cirrus' data structure
  src/app/functions/server/getExperiments.ts
  src/app/hooks/useGlean.ts
  src/app/layout.tsx
  src/contextProviders/experiments.tsx
Labels: Review: XS

#5484 Import translations from l10n repository (2025-01-19)
  locales/ko/exposure-card.ftl
  locales/ko/fix.ftl
  locales/ko/settings.ftl
Labels: l10n

#5510 Add reminder to check both flag states
  .github/pull_request_template.md
Labels: Review: µ

#5531 Import translations from l10n repository (2025-01-28)
  locales/ca/add-email.ftl
  locales/ca/app.ftl
  locales/ml/landing-all.ftl
Labels: l10n

#5546 Properly skip unstable Node dependabot updates
  .github/dependabot.yml
Labels: Review: µ

#5524 MNTOR-3924: Plus Expiration heads-up page
  .storybook/preview.tsx
  locales-pending/plus-expiration.ftl
  package-lock.json
  package.json
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/PlusExpiration.stories.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/RenewalShell.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/RenewalShell.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/View.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/View.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/actions.ts
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/page.tsx
  src/app/(proper_react)/(redesign)/terms/expiration-offer/ExpirationOfferTerms.stories.tsx
  src/app/(proper_react)/(redesign)/terms/expiration-offer/View.module.scss
  src/app/(proper_react)/(redesign)/terms/expiration-offer/View.tsx
  src/app/(proper_react)/(redesign)/terms/expiration-offer/page.tsx
Labels: Review: XS

#5558 Use Ruby version syntax for Dependabot-Docker
  .github/dependabot.yml
Labels: Review: µ

#5563 Implement forgotten isOnExpirationList check
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/page.tsx
Labels: Review: µ

#5574 Import translations from l10n repository (2025-01-31)
  locales/tr/email-strings.ftl
Labels: l10n
