Repository mozilla/blurts-server, pull requests merged in 2025-02, with the labels that each got.

#5565 Some refinements for the renewal page
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/RenewalShell.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/View.module.scss
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/View.tsx
  src/app/(proper_react)/(redesign)/terms/expiration-offer/View.tsx
Labels: Review: XS

#5582 Import translations from l10n repository (2025-02-03)
  locales/sk/settings.ftl
Labels: l10n

#5584 Fix flaky subscription renewal tests
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/PlusExpiration.test.tsx
Labels: Review: XS

#5585 Update Mozilla logo in website and email footer
  public/images/email/mozilla-logo-bw.png
  src/app/(proper_react)/images/mozilla-logo.svg
Labels: Review: µ

#5587 MNTOR-4028: Allow renewing after receiving an expiration email
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/page.tsx
  src/db/tables/subscriber_churns.ts
Labels: Review: XS

#5600 Import translations from l10n repository (2025-02-09)
  locales/ml/app.ftl
  locales/ml/email-strings.ftl
Labels: l10n

#5601 Import translations from l10n repository (2025-02-10)
  locales/id/add-email.ftl
  locales/id/app.ftl
  locales/id/bento.ftl
  locales/id/dashboard.ftl
Labels: l10n

#5597 *Actually* fix flaky Plus subscription tests
  src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/PlusExpiration.test.tsx
Labels: Review: µ

#5591 MNTOR-3971: Use last optout date instead of last update
  src/apiMocks/mockData.ts
  src/app/(proper_react)/(redesign)/(authenticated)/admin/qa-customs/onerepConfig.tsx
  src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardPlusUsers.stories.tsx
  src/app/api/mock/onerep/config/config.ts
  src/app/api/v1/admin/qa-customs/onerep/route.ts
  src/app/components/client/exposure_card/ExposureCard.test.tsx
  src/app/components/client/exposure_card/ScanResultCard.tsx
  src/app/functions/server/onerep.ts
  src/db/tables/onerep_scans.ts
  src/db/tables/qa_customs.ts
  src/knex-tables.d.ts
Labels: Review: XS

#5624 Import translations from l10n repository (2025-02-16)
  locales/nn-NO/settings.ftl
Labels: l10n

#5638 Dedupe Sentry logs about missing Cirrus user ID
  src/app/(proper_react)/(redesign)/(public)/layout.tsx
Labels: Review: XS

#5640 MNTOR-3946: State that we don't endorse breached sites
  src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailView.tsx
  src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailsView.test.tsx
Labels: Review: XS

#5658 MNTOR-4066: Turn cronjob into long-running interruptible task
  package.json
  src/scripts/cronjobs/emailBreachAlerts.tsx
Labels: Review: XS

#5663 Revert margin shrinking in desktop header
  src/app/(proper_react)/(redesign)/(public)/PublicShell.module.scss
Labels: Review: µ
